### PR TITLE
Replace Audacity branding in Innosetup

### LINKED ISSUE #502: Audacity logo used in Windows installation dialogs
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

latest master build for Tenacity  https://github.com/tenacityteam/tenacity/actions/runs/1145691475

### Describe the bug.

1. Install latest master build
2. Observe Audacity Logo and not Tenacity in the installation dialog
image

3. Next dialog window
image
Not only Audacity logo - bit many mentions of "Audacity"

4. Next dialog window
image

5. And the next dialog window
image

6. and the next
image

7. and this one has audacity references (more than can be seen here)
image

8. and now the final installation window with a big Audacity icon
image

### Expected behavior

Tenacity logos and Tenacity references throughout

### OS

Windows 10

### Additional context

_No response_

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

### PR DESCRIPTION
**Pull request by fugidev**
Resolves: #502

Replaces the large and small logos in the Windows installer with Tenacity's.

// EDIT: 1x scale screenshots
tenacity-100-1
tenacity-100-2

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
This looks good. I'll also pass this by @akleja who made the logos and may have a better perspective on this.

**Review by n0toose — DISMISSED** [review]

**Comment by akleja** [comment]
There seems to be some issue with the scaling of the images. The logo isn't square and the bitmap is up-sized. The size seems correct at least according to the info I could find, so I guess it might be a dpi issue?

Might not be the biggest of issues, but here is a resource that might help:
https://stackoverflow.com/questions/26543603/inno-setup-wizardimagefile-looks-bad-with-font-scaling-on-windows-7

**Comment by fugidev** [comment]
Yes, my monitor is indeed scaled. But the logo should be square. Did you only look at the screenshots or did you run it yourself / check the files? @akleja

Thank you for the link you provided, that will be useful. I will add scaled versions later.

**Comment by akleja** [comment]
I only looked at the screenshots, I don't have a windows setup unfortunately.
The files look fine but in the screenshot things are a bit squashed.

**Comment by fugidev** [comment]
As you suggested, adding scaled versions of these images should probably improve it. I will take a look later and test different scaling settings.

**Comment by fugidev** [comment]
Added scaled images for 100%, 125%, 150%, 200%. I tested all of them in a VM, looks way better now.

**Comment by Be-ing** [comment]
Is it possible to use one SVG file instead of a bunch of rasterized versions?

**Comment by fugidev** [comment]
> Is it possible to use one SVG file instead of a bunch of rasterized versions?

According to the docs, only bitmap files are supported

**Review by akleja — DISMISSED** [review]
Looks good to me

**Comment by Be-ing** [comment]
> According to the docs, only bitmap files are supported

Ugh. Alright, let's go with multiple bitmaps at different scales then.

**Review by Be-ing — DISMISSED** [review]

**Pull request merged**
