### PR TITLE
Add FossHub Link for older Audacity version to README.md

### PR DESCRIPTION
**Pull request by gregorylearns**
to include link to fosshub's older version page.

took me a while to find audacity 3.0.2 there

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code\*
- [ ] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by fitojb** [comment]
+1. I don’t trust Muse Group to retain easily accessible links to the older versions.

**Comment by gregorylearns** [comment]
> +1. I don’t trust Muse Group to retain easily accessible links to the older versions.

Yes. I didn't see any download link to older versions on the Audacity website, had to sift through fosshub links

**Comment by LWinterberg** [comment]
> I didn't see any download link to older versions on the Audacity website

image
https://www.audacityteam.org/download/windows/

image
https://www.audacityteam.org/download/mac/

image
https://www.audacityteam.org/download/

image
on all download pages linking to 
https://www.audacityteam.org/download/legacy-windows/
https://www.audacityteam.org/download/legacy-mac/

and also https://github.com/audacity/audacity/releases

**Comment by n0toose** [comment]
Hey, thanks for your pull request, you should read up on how to sign our DCO so that we can get your change included :)

**Pull request closed without merging**
