### PR TITLE
New mouse pointers and zoom icons

### LINKED ISSUE #287: Change selection Icon
image

This looks outdated and scales horribly on high resolution displays.

---
Info
OS: Windows 10
Display: 1920×1080p

### PR DESCRIPTION
**Pull request by akleja**
**Cursors**
* Adds cursors for selection adjustment instead of relying on system cursors
  Windows selection cursors looked outdated

* Adds smoothing cursor to draw tool instead of relying on system cursors

* Replaces most old mouse cursors
 New ones made to match toolbar icon

new cursors all

**Icons**
* Replaces zoom icons in FreqWindow
  New ones made to work on both dark and light theme

freq

**Explanation**
Cursors with red background are changed slightly, magenta bigger changes, green entirely new, and blue completely unchanged.

I've changed style of the RearrangeCursor to be more intuitive than the hand. As far as I can see the hand isn't really used in any major way (if at all) before the affordances bar was introduced, so it shouldn't cause problems with existing users.

Resolves: #287 

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
You did this faster than me, but one of the things that held me back, personally, is how this would look with dark themes on other operating systems.

**Comment by akleja** [comment]
Oh I didn't know you were working on it, sorry!
Yeah I went with the old white fill with black outlines. While perhaps not ideal, it's clear and visible. 
One alternative route would be to include mouse pointers in the themes. There are some already defined in there, but I'm not sure if they're ever uses.
What would make a huge difference appearance-wize would be to implement a more modern file format for cursors whith higher transparency bit dept. But that's a lot of work.
I've begun drawing the rest of the cursors to and will add them in a different pr when they're done.

**Comment by n0toose** [comment]
> Oh I didn't know you were working on it, sorry!

It's fine, I barely made any progress because of the hold-up. I'm not 100% sure about this. (More feedback needed.)

**Review by nbsp — DISMISSED** [review]
Works on my Windows 10 VM. Looks nice too!

**Comment by akleja** [comment]
I've posted some alternatives to these cursors in the linked issue #287, and also a full set of new cursors.
I could use some feedback on them, and if the new ones are preferred I'll replace the ones in this PR

**Review by n0toose — DISMISSED** [review]

**Comment by nbsp** [comment]
@akleja do you want to add the rest of the pointers to this PR?

**Comment by akleja** [comment]
I could add them to this one, or make a separate one for them if you want to merge these right away. But if I shall add them to this one it will have to be tomorrow, since I'm not at home right now.
Also I was kinda waiting for some more feedback on the other cursors, but have prepared the set I'd preferred based on the discussion so far.

**Comment by nbsp** [comment]
> I could add them to this one, or make a separate one for them if you want to merge these right away. But if I shall add them to this one it will have to be tomorrow, since I'm not at home right now.
> Also I was kinda waiting for some more feedback on the other cursors, but have prepared the set I'd preferred based on the discussion so far.

I'd prefer it if you add the rest of the icons to this PR, please. No rush :)

**Comment by nbsp** [comment]
When you update this commit, please rename it to something less specific, like `Add custom mouse pointers`

**Review by AnotherFoxGuy — DISMISSED** [review]
Works fine on Windows 10
img

**Comment by akleja** [comment]
Updated and ready for review!

**Review by nbsp — APPROVED** [review]
Amazing work, thank you! :D

**Review by n0toose — APPROVED** [review]

**Comment by Semisol** [comment]
Please wait, I'll review.

**Review by Semisol — APPROVED** [review]

**Comment by n0toose** [comment]
For future reference, it's generally a good idea to add other peoples' sign-offs as well (provided that they have signed off their original commits) and adding other contributors as Co-authors by using `Co-authored-by: Previously Used Name Alias <previously.used.email.address@example.com>`. Just for the sake of consistency.

**Comment by akleja** [comment]
@panos Okay! I'm not sure how this applies to these changes though. Do you mean those who participated in discussions/testing, or those who made the original icons? Just trying to understand what you mean

**Comment by akleja** [comment]
@panos Ok I think I understand why I'm confused. I had included the zoom icons in my local repo since way before, and was unaware your PR with the same issue.
I thus didn't base my changes on your PR, but since you made those changes alongside me it doesn't matter to me.
Just tried to figure out what you meant.

**Pull request merged**
