### PR TITLE
Remove libuuid

### PR DESCRIPTION
**Pull request by n0toose**
Was looking at libraries that could be updated or upstreamed and we seem to have missed that library.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
Oops, I forgot to `git add` the changes I made to the CMake files.

**Review by Semisol — APPROVED** [review]
Compiles and works.
I'll give it the go because it is a simple library removal (that is not used in the current codebase).

**Review by purplesyringa — APPROVED** [review]
Did they really have an unused vendored library? Wow.

**Comment by n0toose** [comment]
> Did they really have an unused vendored library? Wow.

No, it wasn't unused, we made it unused after we got rid of the telemetry. We just forgot the library in there. :D

**Comment by fossdd** [comment]
Ah. Funny.

**Pull request merged**
