### PR TITLE
New Dynamic Compressor Effect

### PR DESCRIPTION
**Pull request by mmmaisel**
This is a rebased version of my Compressor pull request for Audacity that
will not make it into Audacity due to CLA issues.

This effect is in development for over one year now and was already
polished with help of the audacity-devel mailing list.

The "Dynamic Compressor" effect is a downward compressor that, in
constrast to the existing compressor, behaves like somebody expects from
an analog compressor. It is implemented in a new effect not break existing
legacy chains.

In contrast to the existing compressor:
* Thresholding works.
* Stereo channels are compressed as stereo instead of dual mono.
* Wide (logarithmic where necessary) ranges for user settings.
* Lookahead and hold support.
* Working compression by peaks.
* Preview of the output waveform.

The new effect has two envelope detectors, a new one which is based on
an analog PT1 compressor and the legacy envelope detector from the old
compressor effect. Additionally, you can chose between RMS and peak
detection.

I extracted two widgets into separate classes. They are
both integrated into ShuttleGUI so they can be used elsewhere as well.

The SliderTextControl widget is a slider with attached textbox similar
to those in the noise reduction effect GUI. It allows horizontal and
vertical layout as well as linear and logarithmic scales.
It is used for all slider textbox combos on the attached picture.

The Plot widget can be used to easily plot some graph to the screen.
It handles drawing the axes, the plot area, a grid and all conversions
from the graph values to screen coordinates. Plotting multiple graphs in
one widget is possible as well.
This widget is used for the two plots in Compressor Effect.

Envelope detectors and sample preprocessors (RMS and sliding-max)
are separate classes to keep the code modular and extensible.
Internally, the effect uses a four stage pipeline to buffer audio data.
This might be over-complicated for offline processing but allows unified
offline and realtime code-paths.

Realtime preview is supported but currently disabled due
to some limitations in the RealtimeEffectManager which cause 
bad user experience due to high processing latency (up to several minutes)
in the effect at some settings.

Main probleme here is, that the RealtimeEffectManager gives the effect
a small block, e.g. 256 samples, and expects the same amount of samples
in return. So if an effect like my compressor has a high processing
latency, there can be an initial silence for over one minute which the
users will think is a bug. Any changes made to the effect settings will
only take effect after this long time as well.

A possible solution would be latency compensation in the
RealtimeEffectManager so that the effect can request the required
amount of samples in advance at the beginning or when the user changes
settings. The silence at the beginning can then be discarded so that
users do not notice it. But this is out of scope of the compressor
effect changes.

- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] The code in this pull request is licensed under "GPLv2 or any later version"

### CODE REVIEW

**Comment by mmmaisel** [comment]
Currently, this does not build due to conan.

**Comment by cookiengineer** [comment]
Phew, these are a lot of changes. Maybe we need a valgrind integration and some unit tests(?) that can verify that the code doesn't introduce leaks or problems with recursive loops in future to speed big PRs like this one up.

@mmmaisel I'll get back to you as soon as I can, but need a bit of time to verify that everything works with your changes.

**Comment by peepo5** [comment]
once this is checked, it could be put into experimental branch or something. Just an idea :<

**Comment by ajayyy** [comment]
As #47 is now merged, please add the following to your PR description:

```
- [ ] The code in this pull request is licensed under "GPLv2 or any later version"
```

**Comment by Be-ing** [comment]
This PR seems to have gotten messed up somehow, I think with the renaming of the repository. Maybe try closing this and opening a new one?

**Comment by mmmaisel** [comment]
Trying to recreate

**Pull request closed without merging**
