### PR TITLE
Replace "org.audacityteam.audacity" with "org.tenacityteam.tenacity".

### PR DESCRIPTION
**Pull request by CHJ85**
*(short description of the changes and the motivation to make the changes)*
In order to avoid issues white building and packaging Tenacity, I've replace "org.audacityteam.audacity" with "org.tenacityteam.tenacity".

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by ajayyy** [comment]
Contains same changes as https://github.com/tenacityteam/tenacity/pull/144

**Comment by caughtquick** [comment]
Please sign your commits using `git commit -s`.

**Comment by CHJ85** [comment]
@caughtquick Sure. But @ajayyy is right. #144 contains the same changes. I wasn't aware of that. So you might wanna go ahead and apply that one instead.

**Comment by caughtquick** [comment]
> @caughtquick Sure. But @ajayyy is right. #144 contains the same changes. I wasn't aware of that. So you might wanna go ahead and apply that one instead.

Could you please close this one :)

**Pull request closed without merging**
