### PR TITLE
Fixes for building with de-vendored upstream PortAudio

### PR DESCRIPTION
**Pull request by Be-ing**
Small changes split from #228 for building with upstream PortAudio 

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
Wait, this kills off MIDI support, doesn't it?

**Comment by Be-ing** [comment]
No, this only disables EXPERIMENTAL_MIDI_OUT, not USE_MIDI.

**Review by n0toose — DISMISSED** [review]

**Comment by n0toose** [comment]
I think I got something wrong and I can't directly push to master...

Can you do that instead? I approved this because this works and I'm way too afraid to mess something up or issue a dozen force-pushes so that GitHub thinks it's okay.

**Comment by Be-ing** [comment]
Let's just merge this with #228

**Pull request closed without merging**
