### PR TITLE
Add Weblate Support

### LINKED ISSUE #125: Manage localization with Weblate
To ease the updating of translations, I suggest using Weblate, either its SaaS ("Hosted") instance or a dedicated server install.

### PR DESCRIPTION
**Pull request by emabrey**
Resolves: #125

See the issue for discussion, but essentially this will let us use Weblate to manage gettext strings.

- [x] The code in this pull request is licensed under "GPLv2 or any later version"\*
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

### CODE REVIEW

**Review by fossdd — DISMISSED** [review]
Okay, here is the project: https://hosted.weblate.org/projects/tenacity/tenacity/

**Comment by falkTX** [comment]
Won't this cause many merge conflicts with upstream?

**Comment by fitojb** [comment]
At LibreOffice we never worried about maintaining our strings compatible with OpenOfficeorg

**Comment by falkTX** [comment]
That is because it is a full on rework where a lot of maintainers moved, no?

We still want to keep compatibility with upstream Audacity, at least for the time being. So reducing conflicts is crucial.

**Comment by emabrey** [comment]
> 
> 
> Won't this cause many merge conflicts with upstream?

I don't plan on bringing upstream changes often unless its a security fix. If it's a security fix then we can deal with the hassle. Honestly, I don't want to tie Tenacity to MuseGroup's whim.

Weblate is a valuable dev tool IMO.

image
image

**Comment by emabrey** [comment]
I can attempt to add the removed translations back using Weblate. Let's see if that works.

**Comment by emabrey** [comment]
This PR also swaps "Audacity" with "Tenacity" and "audacityteam.org" with "tenacityteam.org" due to some testing of Weblate usage I did.

**Comment by caughtquick** [comment]
@emabrey sorry unable to review

**Review by ajayyy — DISMISSED** [review]

**Review by Semisol — DISMISSED** [review]
Why is the whole history rewritten? I don't think there is a need to rewrite everything historical because of the DCO.

**Review by nbsp — DISMISSED** [review]
So you're signing-off everyone else's commits? That doesn't make sense to me.

**Comment by emabrey** [comment]
The whole history is rewritten because without doing that the DCO script will tell you to rewrite the whole history instead of just your commits. It literally told me to do HEAD~76 because there have been 76 commits since the last signoff (I assume). I didn't spontaneously decide to rewrite the history.

**Comment by nbsp** [comment]
> The whole history is rewritten because without doing that the DCO script will tell you to rewrite the whole history instead of just your commits. It literally told me to do HEAD~76 because there have been 76 commits since the last signoff (I assume). I didn't spontaneously decide to rewrite the history.

Then that's a problem with the bot, and we could manually pull and merge the branch with git.

**Comment by Semisol** [comment]
> > The whole history is rewritten because without doing that the DCO script will tell you to rewrite the whole history instead of just your commits. It literally told me to do HEAD~76 because there have been 76 commits since the last signoff (I assume). I didn't spontaneously decide to rewrite the history.
> 
> Then that's a problem with the bot, and we could manually pull and merge the branch with git.
That would fail due to protection
but this:
image
so no big worries.

**Comment by emabrey** [comment]
So I can merge this with squash and merge and it will undo all the history rewrites?

**Comment by nbsp** [comment]
> So I can merge this with squash and merge and it will undo all the history rewrites?

Not sure about that. You should just restore everything to the non-signed-off state, then sign-off only the needed commits

**Comment by emabrey** [comment]
Any ideas how? I've tried `git rebase -i` but I keep getting merge conflicts.

**Comment by nbsp** [comment]
You should be able to use `git reflog` to restore to a version of the branch without signoffs.

**Comment by emabrey** [comment]
I used `git pull --force` and `git stash` and I think I've got it fixed.

**Review by emabrey — COMMENTED** [review]
I've looked over this and I think it's ready to merge, just waiting for someone else to look it over.

**Review by Semisol — APPROVED** [review]
There isn't anything major I can't review + looks good so I'll give it the go.

**Review by nbsp — APPROVED** [review]

**Pull request merged**
