### PR TITLE
Toolbar style changes

### PR DESCRIPTION
**Pull request by akleja**
A set of small changes to the UI:
* Makes the background color adjust to system theme even when the color is similar to the theme color
* Removes vertical lines from tooldock
* Removes bevel around transport
* Simpler bevel-less style of the toolbar grabbers

With changes
toolbar_dark
toolbar_light

Without changes:
pre_toolbars0

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
Should I ask people about it on social media for more feedback?

THIS IS AMAZING BTW

**Comment by akleja** [comment]
Yeah that might be helpful, but then a comparison with before/after might be a good idea?
This was originally part of my vertical dock project, but since this is more about style than function it made sense to split things up.

**Comment by fitojb** [comment]
I love how it was implemented by mainly removing code :laughing:
Looks 100× better.

**Comment by akleja** [comment]
It's a bit like spring cleaning :)

**Comment by Be-ing** [comment]
>  but then a comparison with before/after might be a good idea?

Yes please post both before and after screenshots for PRs with significant GUI changes.

**Comment by akleja** [comment]
Comparison screenshot added!

**Comment by fugidev** [comment]
This looks really nice IMO, let's see what other people think!

**Comment by n0toose** [comment]
Should we, maybe, just change the grabber so that it has the dot style as in @marcopavanello's concept, maybe? (see: https://github.com/tenacityteam/tenacity/discussions/448)

Just spitting out ideas.

**Comment by akleja** [comment]
I actually made a dotted style initially, but because of the lack of antialiasing it didn't look nice.
It could be done by adding it to the theme file, or ideally by using a graphics context instead of a drawing context, but the first option isn't ideal, and the second is a huge project. I guess it could be done by creating a gc in memory and copying it from there, but it seems a bit much tbh.

**Review by n0toose — APPROVED** [review]

**Review by fugidev — APPROVED** [review]

**Comment by n0toose** [comment]
Merged. (see c3c5765, cc7c659, 55f5ef8, a120a51)

**Comment by Be-ing** [comment]
Thanks for this!

**Pull request closed without merging**
