### PR TITLE
adding --needed flag for arch build

### PR DESCRIPTION
**Pull request by kars0n777**
Pacman shouldn't reinstall packages that the user might already have.

### CODE REVIEW

**Comment by n0toose** [comment]
Please sign the DCO as described in the CONTRIBUTING.md file.

**Comment by n0toose** [comment]
Hey, sorry for being abrupt, was very busy at the time. I see you're new here (as far as contributing to repositories on GitHub is concerned)! Do you need any help with signing-off, maybe?

**Comment by kars0n777** [comment]
Yeah, I'm new and I'm confused to what DCO is and why I'm not authorized to make a pull request

**Review by fossdd — APPROVED** [review]

**Comment by fossdd** [comment]
@n0toose for these small contributions a DCO is not required.

**Comment by Psychosynthesis** [comment]
@fossdd @n0toose 
Excuse me for interfering, but I want to ask, what kind of problem does the ``signed-off-by statement`` specifically solve?

It is quite obvious to me that, for example, the naming of commits must obey the rules, just like messages to commits, and so on...

But specifically ``signed-off-by statement`` looks like a kind of bureaucracy. You have a Licensing file, so why not write in it something along the lines of "by committing to this repository, I agree with... etc."?

I'm asking because I see at least a couple more PRs that, according to the checklist, can't be accepted just because of this signature.

In addition, as far as I can tell, the problem is that after one contributor has created a PR with commits without the specified signature, another developer will no longer be able to correct this PR without perversions, because. there are already commits in this branch... And the author may even abandon work on PR altogether. I know there are ways to overwrite the commit message with other commits, but that doesn't seem like a good solution.

Don't you think that this rule, at least, khhmm... "slows down" the work on the project a little?

**Comment by n0toose** [comment]
> Don't you think that this rule, at least, khhmm... "slows down" the work on the project a little?

<details>
<summary>Off-topic rant</summary>
Too late. I wasn't very much in favor for it either because of how it slowed down things and increased the contribution barrier; The project is already basically dead and the only activity mostly happens in pull requests/issues mostly from people that issue excessively opinionated critics over things like... *checks notes* self-referencing own open-source solutions when figuring out how to solve a problem in Tenacity or... because the people responsible for mirroring this repository to SourceHut quit and we are now bad because we violated the will of the people™, which are precisely the kinds of weirdos that caused us to get excruciatingly exhausted with this entire thing in the first place, as people only abused the many different ways we made ourselves reachable to troll, complain, and demand things like spending my holidays to "get off my ass and stop wasting time" to please some politically radical person from Brazil for free instead of spending time with friends & family.

The rule was there for a good reason, it is basically there to better protect the work of the author and reestablish that we acknowledge that this work was given to us by someone else. You can read an article about it [here](https://www.secondstate.io/articles/dco/).

Does it hold any legal basis; I don't know, I am not a lawyer. Do I know of any alternatives? No. I was (and still am, apparently) a huge pain about upholding agreed upon rules until they are amended or completely removed, as I would previously get publicly confronted (on top of drama that got so bad to the point where we got articles written about it) if I did not do that and the sent changes by other people would be forcibly removed, further putting off potential contributors who also spent time and effort for this.

If you think this is bad, which I think it is, as it put off many contributors irreversibly and resulted in tons of lost hours of effort on all ends (even if it should be clear to you that the onus is obviously ***not on us***), then you are more than free to contest the rules, or fork it and run it on you own, as the Tenacity Audio Editor is effectively abandonware (as mentioned in our organization's description and our repository's description) and I am the only person who responds at this point for some reason.
</details>

---

P.S. @fossdd, I get that you are saying this specifically because the Audacity people said the same thing to you after you submitted a pull request with a minor document change, but you should remember that this project was literally specifically built out of spite of Audacity's practices over things like "Small contributions are small, so therefore, copyright does not exist anymore".

**Comment by n0toose** [comment]
I handed over administrator access over to this repository to @fossdd. He is free to merge this pull request on his own accord if he deems it appropriate. Peace ✌🏻

**Comment by n0toose** [comment]
For reasons of future-proofing and after doing some additional research into the topic myself, I enabled [sign-off on web-based commits](https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/) to prevent any further confusion in the long run. This feature has been available for less than a month, could've prevented such a confusing situation and I was not previously aware of it, apologies.

**Pull request closed without merging**
