### PR TITLE
Fix CI build

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Applied the same fix for #699 to the cmake build

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
you're free to just merge this if the CI builds pass i think

**Review by n0toose — APPROVED** [review]
Mostly syntax-related improvements, approving.

**Comment by n0toose** [comment]
Isn't it a bit inconsistent to still have the Windows certificate stuff but not the Apple notarization stuff, BTW?

**Comment by AnotherFoxGuy** [comment]
> Isn't it a bit inconsistent to still have the Windows certificate stuff but not the Apple notarization stuff, BTW?

I didn't change any of the singing stuff in this PR

**Comment by n0toose** [comment]
Apologies, got confused by the Web UI.

**Comment by n0toose** [comment]
Or, wait, no, it was just me noticing the Windows stuff being there while the macOS stuff got removed in the previous PR. Anyways, that's beyond the scope of this PR and bikeshedding at this stage really isn't that good of a strategy.

**Comment by AnotherFoxGuy** [comment]
> you're free to just merge this if the CI builds pass i think

I don't have the permission to merge PRs

**Comment by n0toose** [comment]
ba dum dee, ba dum boo, now you do!

**Comment by n0toose** [comment]
awesome! (please try to be considerate of the commit message rules though, thx)

**Pull request merged**
