### PR TITLE
Change the Tenacity alpha version way down to 0.1.0

### PR DESCRIPTION
**Pull request by n0toose**
I did not manage to spot any "booby traps" that would break certain features of Tenacity depending on the reported version.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
P.S. I don't think that starting off with the big `1.0.0` release is a good idea, I think we are too early for this development-wise.

**Comment by Semisol** [comment]
> P.S. I don't think that starting off with the big `1.0.0` release is a good idea, I think we are too early for this development-wise.

Yep, that's for stable

**Comment by n0toose** [comment]
> Yep, that's for stable

We have "alpha" and "beta" releases for that, but releasing a "0.1" stable version should probably be enough to signify to people that "hey, we are still on a very early stage".

**Comment by n0toose** [comment]
Wait, I forgot about Flathub and other places.

**EDIT:** Should be fine. (?)

**Review by nm17 — APPROVED** [review]

**Comment by fugidev** [comment]
I support starting with 0.1.0 - since it seems to be ok, should we just do it?

**Comment by Be-ing** [comment]
I was thinking we would follow Audacity's version numbers, but I don't have a strong opinion on this.

**Comment by nbsp** [comment]
May be made irrelevant by #396.

**Review by fossdd — APPROVED** [review]
0.1.0 would fine

**Comment by n0toose** [comment]
> May be made irrelevant by #396.

Can we still start from 0.1.0, even with the new versioning method?

**Comment by nbsp** [comment]
> > May be made irrelevant by #396.
> 
> Can we still start from 0.1.0, even with the new versioning method?

Sure, but I think it's best that #396 is merged and we tag the release as `0.1.0`.

**Pull request closed without merging**
