### PR TITLE
Add `funding.yml` and badge to `README.md`

### PR DESCRIPTION
**Pull request by emabrey**
Signed-off-by: caughtquick <me@caughtquick.tech>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

### CODE REVIEW

**Review by caughtquick — APPROVED** [review]

**Review by fugidev — APPROVED** [review]

**Review by Semisol — APPROVED** [review]

**Comment by Semisol** [comment]
I'll merge.

**Comment by falkTX** [comment]
Money complicates everything.. donations will have to be clarified very well where they go.
All it takes is messing up once for people to not trust tenacity anymore.

**Comment by Semisol** [comment]
Oh-
Thanks.

**Comment by Semisol** [comment]
@falkTX Open Collective makes transactions transparent.
I still would request extensive reviewing internally.

**Comment by caughtquick** [comment]
Let's move this to #265.

**Comment by emabrey** [comment]
You can view all transactions, incoming or outgoing (donations or expenses) here: https://opencollective.com/tenacity/transactions

**Pull request merged**
