### PR TITLE
Changed Audacity*.{cpp,h} to Tenacity*.{cpp,h} in src/

### PR DESCRIPTION
**Pull request by DemonicSavage**
I removed many references to Audacity from the src/ folder.
I get that this is very intrusive, but it had to be done
sooner or later.

Reference-to: https://github.com/tenacityteam/tenacity/issues/508
Signed-off-by: Gabriel Felipe Huwe <gabrielhuwe@gmail.com>

Part of: https://github.com/tenacityteam/tenacity/issues/508

References to Audacity are a blocker for 0.1.0, so I renamed some files.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by caughtquick** [comment]
Thanks for doing all this

**Comment by caughtquick** [comment]
Don't worry about the macOS build fail, that's a common issue with CMake, not something you changed

**Comment by DemonicSavage** [comment]
Sure. Let me know if there are anything that could be added to this PR!

Everything alright with the DCO bot? It seems to be waiting.

**Review by n0toose — APPROVED** [review]
I think it's time. Let's go for it. I'll let this PR rest for ~5 days or so, just in case anybody else disagrees.

**Review by caughtquick — APPROVED** [review]

**Comment by TheEvilSkeleton** [comment]
> I think it's time. Let's go for it. I'll let this PR rest for ~5 days or so, just in case anybody else disagrees.

Just a reminder, no one disagrees.

**Pull request merged**
