### PR TITLE
Remake of all the themes

### LINKED ISSUE #311: Gray bars do not adjust to the theme colors
After I compiled the last version with all current changes, gray bars were displayed in the gui during recording (see screenshot).
The whole independent of the theme.
Bildschirmfoto vom 2021-07-19 13-36-24

Custom Theme File...
ImageCache

### PR DESCRIPTION
**Pull request by akleja**
Updates of all the themes

* A remake of the dark theme meant to utilize more standardized colors for
dark themes and improve readability. Also all icons are redrawn to make them a bit cleaner.
* A remake light themes made to match the dark theme. 
* A gentle remake of the High contrast theme, though sparsely altered.
* Classic theme stays the same, but with added new colors for "Wave track affordances"
* Removal of hard coded black borders
* Alterations to the highlights of the bevels around TrackVRulerControls
    This could've been done in a more elegant way, but I tried to keep changes minimal

This is intended as a drop in replacement for the old themes, and will not resolve pre-existing issues related to how themes are applied.
The problems on mac and windows aren't introduced by these alterations of the themes, and are due to how wxWidgets handles native controls and recognizes themes. If I'm not mistaken it's supposed to be resolved in the next (3.2) release of wxWidgets.

To do:
~~* Some elements in the dark theme that I couldn't locate are coloured bright magenta for now. If they aren't found I'll replace them with the old colors to be on the safe side.~~
~~* Only tested on linux~~

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by Semisol** [comment]
Please wait a little bit.

**Review by Semisol — DISMISSED** [review]
On macOS there seems to be some problems.
image
It also doesn't inherit the dark theme on the pickers etc (Old applications have this bug, is there any way it can be fixed?)

**Comment by AnotherFoxGuy** [comment]
This is how it looks on windows

abc

**Comment by akleja** [comment]
@semisol Ok that's strange, it doesn't seem to pick up the theme at all.

Those pickers and scrollbars haven't ever been themeable as far as I know. since wxWidgets uses native controls for those. That's a bigger issue that is out of the scope for this pr.

The dark theme will only look good on a system with a dark theme unless we migrate from wxWidgets.

**Comment by akleja** [comment]
@Semisol I think I've find a possible explanation to why the theme wasn't loaded when you tried it.
If you have another instance of the program running when your launching the recently built one, the theme cache isn't updated.
If you could make sure you have no other running instance of tenacity/audacity when launching the build of this, and see if it changes anything it would be really helpful.

**Comment by ZeroDot1** [comment]
Hi @akleja, It looks good and I like it.

I quickly [grabbed the files](https://raw.githubusercontent.com/akleja/tenacity/98369cca4d202e070c2ee71a80e097a9b04dd415/src/DarkThemeAsCeeCode.h) and compiled the whole thing on my system (Arch Linux), it looks good except for the gray bars check this out: https://github.com/tenacityteam/tenacity/issues/311
Bildschirmfoto vom 2021-07-19 21-17-25

**Comment by akleja** [comment]
Hi @ZeroDot1, thanks. Do you by any chance have "Blend system and Audacity theme checked"? I notice the colors look a bit different.
Ok, thanks, will try to incorporate those colors into the theme in a while!

**Comment by ZeroDot1** [comment]
Bildschirmfoto vom 2021-07-19 21-37-01

**Comment by ZeroDot1** [comment]
Hi @akleja, 
> Do you by any chance have "Blend system and Audacity theme checked"?

Yes I have activated Blend system and Audacity theme because the colors are a bit darker and it looks better and is easier to use.

**Comment by ZeroDot1** [comment]
Bildschirmfoto vom 2021-07-19 21-42-47
Bildschirmfoto vom 2021-07-19 21-17-25

**Comment by akleja** [comment]
Okay cool, thanks! Just wondered why it looked different.

**Comment by Semisol** [comment]
> If you have another instance of the program running when your launching the recently built one, the theme cache isn't updated.

Nope, did not

**Comment by akleja** [comment]
@Semisol Ok thanks! I'm still prone to believe it's som kind of caching/tmp file issue since none of the graphics present in the old dark theme remains in this build (to my knowledge), yet it still shows up in your system.
Ether that or I've missed a big chunk of mac-specific theming hidden in the codebase.
Any suggestions and further testing on macOS are welcome

**Comment by akleja** [comment]
@ZeroDot1 I've added some colours to the bars now

**Comment by Semisol** [comment]
> @Semisol Ok thanks! I'm still prone to believe it's som kind of caching/tmp file issue since none of the graphics present in the old dark theme remains in this build (to my knowledge), yet it still shows up in your system.
> Ether that or I've missed a big chunk of mac-specific theming hidden in the codebase.
> Any suggestions and further testing on macOS are welcome

I think these are the main problems:
1. You cannot theme native things
2. macOS I think has a feature where if your application is pre dark-mode, the user dark mode setting does not apply and it is ALWAYS light mode.

**Comment by akleja** [comment]
@Semisol 
1. Yes this applies to all platforms, and affects the dropdown.
2. Might be something to look into, but it's beyond my knowledge at this time how to address.

One mystery still remains: In your screenshot none of my theming is applied, for example text/background colors, icons etc. That is the main thing I'm trying to understand why as of now.

**Comment by ZeroDot1** [comment]
Hi @akleja It works very well, perfect.

Thank you for your good work.

Bildschirmfoto vom 2021-07-19 22-57-11

**Comment by akleja** [comment]
@ZeroDot1 Cool! Thanks a lot for testing!

**Comment by Semisol** [comment]
Problem, I didn't checkout the branch you made.

**Comment by akleja** [comment]
@Semisol That might explain things. I was getting so confused

**Comment by Semisol** [comment]
image

**Comment by awslabspl** [comment]
> On macOS there seems to be some problems.
> image
> It also doesn't inherit the dark theme on the pickers etc (Old applications have this bug, is there any way it can be fixed?)

By any means its not a bug. Its just that ( with the release of macOS Catalina ) theming was redesigned and those apps you are talking about uses old way of theming.

**Comment by ZeroDot1** [comment]
@akleja Nice :heart: !

**Comment by CHJ85** [comment]
Works fine in Linux. Problem seems to be exclusive to Mac and Windows.
Anyway. Do you think you could make the buttons pop out a little?
I like how they've done it in Audacium's Pro Tools theme:

audaciumtheme

But maybe we should just wait and see what upstream Audacity does with their themeing.
Although that could take forever.

**Comment by akleja** [comment]
Cool! Those problems on mac and windows aren't introduced by these alterations of the themes, and are due to how wxWidgets works. I believe some of them are solved upstream in wxWidgets and planned to be included in the next release whenever that comes out.
What I'm looking for here is problems introduced by these themes. Like strangely coloured items, bugs, mistakes etc.
I don't think I'll make any huge stylistic alterations at this point though, mostly fixes and tweaks, unless more people want big changes. I'm trying to make themes that will blend with many different themes/environments, and those types of 3d buttons does not imo.

**Comment by CHJ85** [comment]
@akleja Right. But the thing about buttons popping out like this − and the reason why so many apps take this approach, is that it makes the buttons more visible hence easier for people with poor eyesight. And besides, it makes the app easier to use late at night when your eyes are tired.
I mean, for me it doesn't really matter. It's all the same. But I was just thinking. Because you're making changes to these themes anyway, so why not.

**Comment by akleja** [comment]
I see your point. But do you mean that the buttons should have a different color to the background? That I might be okay with, but the 3d effect I can't say I'm fond of.
Wouldn't it however suffice with the highlight that appears when hovering over a button?

**Comment by CHJ85** [comment]
Idk about a highlight on hovering effect. That sounds annoying.
But I was actually referring to the 3D effect. But if you're not too fond of it, then skip it.
However, what if you add the Pro Tools theme to Tenacity and see what people have to say about it?
Here's the code: https://github.com/SartoxOnlyGNU/audacium/blob/master/src/ProToolsThemeAsCeeCode.h

**Comment by akleja** [comment]
Have you tried the themes in this PR? The highlight is just a slight visual feedback, and not done in an overly aggressive way.
hover


The pro tools themes could fairly easily be added, but adding more themes should probably be done in another PR. Or perhaps improving the feature of loading custom themes.

**Comment by CHJ85** [comment]
Yes, that highlight looks nice and should work just fine.
And I don't think the pro tools theme need to be included. I like it but it looks incomplete.
I was just using it as a reference to the button effect.

**Comment by akleja** [comment]
Perfect!
Yeah I think it would be better to work on improving the custom theme loading rather than adding extra themes.

**Review by ajayyy — APPROVED** [review]

**Comment by Semisol** [comment]
I'll be reviewing in a minute, hang tight.

**Review by n0toose — APPROVED** [review]
LGTM. Some additional reviews may be a good idea.

**Review by caughtquick — APPROVED** [review]
It works fine for me. This is a beautiful improvement over the original dark theme. Thanks for doing this @akleja.

**Comment by akleja** [comment]
I'm just glad to be able to contribute :)

**Comment by n0toose** [comment]
Merged in f30d516a6432b49044c502214e973d0d6e3d5c76.

Apparently, the practice of force-pushing a modified set of changes to the original tree before merging them upstream is correct.

**Pull request closed without merging**
