### PR TITLE
Add Dynamic Compressor effect

### PR DESCRIPTION
**Pull request by mmmaisel**
This is a rebased version of my Compressor pull request for Audacity that
will not make it into Audacity due to CLA issues.

This effect is in development for over one year now and was already
polished with help of the audacity-devel mailing list.

The "Dynamic Compressor" effect is a downward compressor that, in
constrast to the existing compressor, behaves like somebody expects from
an analog compressor. It is implemented in a new effect not break existing
legacy chains.

In contrast to the existing compressor:
* Thresholding works.
* Stereo channels are compressed as stereo instead of dual mono.
* Wide (logarithmic where necessary) ranges for user settings.
* Lookahead and hold support.
* Working compression by peaks.
* Preview of the output waveform.

The new effect has two envelope detectors, a new one which is based on
an analog PT1 compressor and the legacy envelope detector from the old
compressor effect. Additionally, you can chose between RMS and peak
detection.

I extracted two widgets into separate classes. They are
both integrated into ShuttleGUI so they can be used elsewhere as well.

The SliderTextControl widget is a slider with attached textbox similar
to those in the noise reduction effect GUI. It allows horizontal and
vertical layout as well as linear and logarithmic scales.
It is used for all slider textbox combos on the attached picture.

The Plot widget can be used to easily plot some graph to the screen.
It handles drawing the axes, the plot area, a grid and all conversions
from the graph values to screen coordinates. Plotting multiple graphs in
one widget is possible as well.
This widget is used for the two plots in Compressor Effect.

Envelope detectors and sample preprocessors (RMS and sliding-max)
are separate classes to keep the code modular and extensible.
Internally, the effect uses a four stage pipeline to buffer audio data.
This might be over-complicated for offline processing but allows unified
offline and realtime code-paths.

Realtime preview is supported but currently disabled due
to some limitations in the RealtimeEffectManager which cause 
bad user experience due to high processing latency (up to several minutes)
in the effect at some settings.

Main probleme here is, that the RealtimeEffectManager gives the effect
a small block, e.g. 256 samples, and expects the same amount of samples
in return. So if an effect like my compressor has a high processing
latency, there can be an initial silence for over one minute which the
users will think is a bug. Any changes made to the effect settings will
only take effect after this long time as well.

A possible solution would be latency compensation in the
RealtimeEffectManager so that the effect can request the required
amount of samples in advance at the beginning or when the user changes
settings. The silence at the beginning can then be discarded so that
users do not notice it. But this is out of scope of the compressor
effect changes.

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] The code in this pull request is licensed under "GPLv2 or any later version"

### CODE REVIEW

**Comment by n0toose** [comment]
Hi, sorry for not addressing your pull request in more than a month, I just wasn't sure what to say and we all got extremely busy. First off, thank you for entrusting your seemingly very hard work to us.

Are you planning to prepare this change for it to be reviewable at any point soon?

**Comment by mmmaisel** [comment]
I wrote this pull request before the build system became annoying and am currently unable to build locally.
As soon as #228 and #300 are resolved I'll rebase and fix this up for review.

**Comment by n0toose** [comment]
> I wrote this pull request before the build system became annoying and am currently unable to build locally.
> As soon as #228 and #300 are resolved I'll rebase and fix this up for review.

Ouch, sorry to hear that and thanks for informing us about it. We'll get back to work and keep you posted, thanks for letting us know (and excuse us once again for the delay)!

**Comment by mmmaisel** [comment]
I rebased and fixed this so it builds now on a Fedora Rawhide VM.
However, this is not tested yet. The automatic tests do not work because of #513.

**Comment by n0toose** [comment]
GOOD LORD, THANKS FOR HELPING US WITH THIS

**Comment by n0toose** [comment]
However, you still need to sign off your commits in order for us to include the changes. In the meantime, we'll review it as-is.

Please run `git rebase HEAD~<number of commits> --signoff` and then force-push once again and it should be good to go for now. :D

**Comment by n0toose** [comment]
Seems good to me.

Would you mind clarifying this part, however?

> Realtime preview is supported but currently disabled due
> to some limitations in the RealtimeEffectManager

**Review by n0toose — APPROVED** [review]
Excellent work!

**Comment by mmmaisel** [comment]
Would you mind clarifying this part, however?

        Realtime preview is supported but currently disabled due
        to some limitations in the RealtimeEffectManager

The problem with realtime preview is, that the RealtimeEffectManager gives
the effect a small block, e.g. 256 samples, and expects the same amount of
samples in return. But in case of the compressor, the effect has to do some
internal buffering to realize lookahead and, in case to the exponential fit
envelope detector, attack time. Until the buffer is filled, the output signal
is simply zero padded as there is no concept of latency or like gstreamers
presentation timestamps yet which would allow the RealtimeEffectManager
to feed in more samples until the buffer is filled and discard the padding
output.

So if a user sets the settings so that there will be a high computational
latency and clicks "realtime preview", there can be silence for several 10 seconds.
Furthermore, if the user changes some settings while realtime preview is active,
it takes again the latency time until the change can be heard.

This would most likely cause bug reports about broken realtime preview since
users hear no audio but see the cursor moving forward in the waveform window,
so I disabled it. Once the RealtimeEffectManager is improved, this can be
easily enabled.

**Comment by n0toose** [comment]
This seems to work well on a bunch of platforms. Waiting any longer doesn't make sense, we'll try to fix things later on if something goes wrong. Thank you for trusting us with your (***amazing***) work like that, @mmmaisel! :D

**Comment by n0toose** [comment]
Rebased the commits on top of master, works. I'll just merge the branch as-is to preserve history.

**Pull request merged**
