### PR TITLE
Fix innosetup build on Windows 10 & Rename to Tenacity

### PR DESCRIPTION
**Pull request by Sebbl0508**
Signed-off-by: Sebastian Rueth <sebastian.rueth@protonmail.com>

When trying to package Tenacity on Windows 10 with Innosetup i got some errors.
So i fixed them and renamed everything (afaik) from Audacity to Tenacity.
Packaging step was performed with VS19
Installing & Uninstalling works on both my Win10 Machines

- [X] I have signed off my commits using `-s` or `Signed-off-by`
- [x] I made sure the code compiles on my machine
- [X] I made sure there are no unnecessary changes in the code
- [X] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [X] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by Sebbl0508** [comment]
I just noticed that #144 already does part of this PR, but keeps the Registry entries with "Audacity"

**Review by fossdd — DISMISSED** [review]
Good catches. As https://github.com/tenacityteam/tenacity/pull/144 is already having merge conflitcts, I think these small fixes goes well. The registry entries are also important.

**Review by nbsp — CHANGES_REQUESTED** [review]
These are two separate issues addressed in the same commit. Could you split them so that one fixes the build, and the other changes the names?

**Comment by Sebbl0508** [comment]
> These are two separate issues addressed in the same commit. Could you split them so that one fixes the build, and the other changes the names?

Ok, so the changes *should* be the same over-all now.

**Review by nbsp — APPROVED** [review]
Some references to Audacity are still changed in the first commit, but I assume that's necessary for the fix to work.

**Review by emabrey — APPROVED** [review]

**Pull request merged**
