### PR TITLE
🎉 Generate manpage with scdoc

### LINKED ISSUE #358: Use scdoc for manpage generation
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
The [manpage](https://github.com/tenacityteam/tenacity/blob/master/help/tenacity.1) seems to only exist as a processed file, and its source is not available. This makes it a bit unwieldy to use or edit, and you can't really read anything when viewing it raw.

**Describe the solution you'd like**
There are many different manpage generators out there, but my personal favourite is [scdoc](https://sr.ht/~sircmpwn/scdoc/), a fast, readable, and manpage-oriented documentation generator. For example, [SwayWM](https://raw.githubusercontent.com/swaywm/sway/master/sway/sway.1.scd) uses scdoc for its manpages.

`scdoc(5)` contains information about the syntax. It's designed to be similar to Markdown, but different, because Markdown is built for HTML.

As far as the installation process goes, the only thing that needs to be added is `scdoc < tenacity.1.scd` (and of course the scdoc dependency).

### LINKED ISSUE #367: Ubuntu CI build broken - missing tenacity.1
- [X] I have read the specified guidelines for issues

**Describe the bug**

Seems the deletion in https://github.com/tenacityteam/tenacity/commit/31fbfeec5245c8371ae1179978d5408b5b2f7e51 is causing build problems: https://github.com/tenacityteam/tenacity/pull/366/checks?check_run_id=3150535166 (#366)

**Additional information (please complete the following information):**
 - GitHub CI Ubuntu job

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
CMake will now generate the manpage if scdoc is installed

Closes #358
Fixes #367

<details>
<summary>Contributor stuff</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

</details>

### CODE REVIEW

**Comment by fossdd** [comment]
For building the manpage in the CI job, you should add: https://github.com/tenacityteam/tenacity/pull/365/files#diff-5933fe574033c94c6e89bda869bcd3a36bad5e790c6e71694370e56e534ca225

**Comment by nbsp** [comment]
> For building the manpage in the CI job, you should add: https://github.com/tenacityteam/tenacity/pull/365/files#diff-5933fe574033c94c6e89bda869bcd3a36bad5e790c6e71694370e56e534ca225

Only the `dependencies.sh` part.

**Review by nbsp — DISMISSED** [review]
There's no need to add the scdoc dependency to the CI.
You might want to add it to the list of dependencies in `BUILDING.md`.

**Comment by nbsp** [comment]
One minor note though: the previous commit is called `Use scdoc for man page generation`, which is similar to this commit message. Perhaps `cmake: Generate man page` would be more appropriate?

**Review by nbsp — DISMISSED** [review]

**Review by nbsp — APPROVED** [review]

**Review by fossdd — APPROVED** [review]

**Pull request merged**
