### PR TITLE
Fix incorrect AudacityCommand's PluginTypeString

### LINKED ISSUE #271: On Windows GitHub Actions build, all plugins are disabled and cannot be enabled
- [x] I have read the specified guidelines for issues

**Describe the bug**
On a clean Windows 10 machine without Audacity previously installed, when I download and extract the Win64 build from GitHub Actions, the menus are missing most actions, and all plugins are disabled and cannot be reenabled.

**To Reproduce**
1. Download https://github.com/tenacityteam/tenacity/suites/3241483574/artifacts/75246671.
2. Extract and run the program.
3. Click on the Generate, Effect, or Analyze menus.

All plugins are missing.

If I open a menu then click Add / Remove Plugins, then try enabling plugins, pressing OK does not enable the plugins, and they again appear as disabled when I reopen Add / Remove Plugins.

**Expected behavior**
All plugins are present.

**Screenshots**

ARKQhJh8QG

firefox_zVqDQUabhN

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity_Windows_64bit_1031847544_7a55a0b.zip

**Additional context**
When building Tenacity myself on Linux, I've noticed in some cases that when swapping between Flatpak Audacity and self-built Tenacity, I would get duplicate plugin warnings and disabled plugins I couldn't enable. Renaming ~/.audacity-data/ and allowing it to be recreated would reset the settings and fix the issue when it happened.

### LINKED ISSUE #283: Plugins are unable to load on certain OS
- [x] I have read the specified guidelines for issues

**Describe the bug**
Plugins are not loaded properly. Upon closer inspection, the issue may lie in the function `NyquistEffectsModule::AutoRegisterPlugins`. PluginManager's mPlugins seems to already have a lot of plugins already present in it at the time of calling `NyquistEffectsModule::AutoRegisterPlugins`.
A good explaination is provided here:
nyquist-1

**To Reproduce**
Clone at the commit af2b77bf47d5ba604e9b0cd6331d0016824cc93f and compile it using CMake (I used CLion IDE, which handles CMake a bit different than vanilla `cmake` CLI tool, but it seems to be happening with the regular CMake as well).
Also a similar issue is present (for me at least) at https://github.com/nm17/tenacity-snap/issues/1 , but it's in a snap package, which might be inconvenient to debug. 

**Expected behavior**
Run tenacity normally, without any bugs with the plugins.

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]: Ubuntu 21.04 amd64
 - Version [e.g. 2.5.1]: af2b77bf47d5ba604e9b0cd6331d0016824cc93f
 - Sound Device [e.g. Windows WASAPI, USB Sound card]: Embedded sound card

**Additional information**
[CMakeCache.txt](https://github.com/tenacityteam/tenacity/files/6829037/CMakeCache.txt)

### PR DESCRIPTION
**Pull request by nm17**
Resolves: #283 and #271

Currently a draft PR, need to check on more devices. Should theoretically fix the issue at hand, but I'm not sure about anything at this point.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
This will require manual testing on Linux machines.

Here's a few steps on how to do this:
- Make sure that Audacity is completely uninstalled.
- Compile and run Tenacity.
- Try to use a plugin.

**Comment by nm17** [comment]
https://github.com/tenacityteam/tenacity/issues/283#issuecomment-881963334

**Review by n0toose — APPROVED** [review]
- Tested on Arch Linux.
- Removed `.audacity-data`.
- lv2 plugins were installed on my system, this review may not be reliable.

**Comment by n0toose** [comment]
Reminder:

> I think Tenacity forked off Audacity during the middle of a plugin management refactor (along with a planning thread), and the current state is broken. I didn't test Audacity master to see if that's broken too (in which case the issue can be reported upstream too). Do you prefer to revert the changes we have so far, or pull in upstream commits as they fix the problem?

**Review by AnotherFoxGuy — APPROVED** [review]
Seems to fix the issue on Windows

**Review by n0toose — APPROVED** [review]
@nm17 claims that they managed to get plugins to work on a "fresh Ubuntu desktop".

**Pull request merged**
