### PR TITLE
Updated About Dialog

### LINKED ISSUE #339: Improve About Window
Proposal for the About Window:

- Replace "Tenacity 3.0.4-alpha" with simply "Tenacity", we can figure out the versioning stuff later.
- Replace the "Tenacity the free, open source, cross-platform software for recording and editing sounds." because the lack of punctuation doesn't make it look that good.
- Add a new header called "Audacity 3.0.4-alpha" right before the Audacity credits.
- The "Tenacity Team" is a very vague term and it's sort of incomplete. There are members in the organization that have contributed a lot but are not actively affiliated or go on-and-off. We should probably name both "team members" and contributors without making "large" distinctions with titles (because this will get messy as we'll start adding more names). We should show our gratefulness to every contributor, especially since they're helping Tenacity get off its feet too much. We can worry about separating this later on. I guess that's much better than "just listing myself" and being done with it.
- We should probably follow the format of `First Name, Last Name (Alias with a hyperlink that leads back to the person's GitHub page or website)` and avoid titles for the time being, we can worry about separating this later on (We can just follow the Audacity format, but not now.).

### PR DESCRIPTION
**Pull request by n0toose**
* Add names (Not final yet)
* Added contact information for every contributor (Not final yet)
* Add "Special Thanks" section
* Improve some logic
* Add notice regarding the alphabetical order

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
People that landed 2-3+ commits of considerable size and effort were included in this list. I may have left someone out on accident or used the wrong contact information. I didn't manage to reach out to everyone very easily, so putting this up for review seemed like the best approach for the sake of efficiency.

**Comment by n0toose** [comment]
I forgot to add one person so far, still waiting on feedback from everyone else.

**Review by fossdd — DISMISSED** [review]
Perfect. Good Changes. Like it to see myself hardcoded in the Tenacity. 😁

**Review by emabrey — CHANGES_REQUESTED** [review]
Made a mistake... oops.

**Review by emabrey — DISMISSED** [review]

**Pull request merged**
