### PR TITLE
Replace Audacity project and building references

### PR DESCRIPTION
**Pull request by ajayyy**
Supersedes https://github.com/tenacityteam/tenacity/pull/144 

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

The description is also changed
image

### CODE REVIEW

**Review by n0toose — DISMISSED** [review]
Merge commits as-is.

**Comment by emabrey** [comment]
I wanted to clarify that I was wrong on the previous PR. There are three "Audacity" marks:

image
image
image

I also want to point out that these trademarks don't make any sense. How could they all have different first use dates lol? Only the first one is registered, the next two are in application for registration, so they aren't (R) yet, but (TM).

**Comment by ajayyy** [comment]
~~Some of the changes didn't make it over in the rebase, I need to look into it~~

That is not the issue

**Comment by ajayyy** [comment]
Build failure was a fluke

**Comment by n0toose** [comment]
> I also want to point out that these trademarks don't make any sense. How could they all have different first use dates lol?

The style of the logo is also "a part of the trademark" (see: the very descriptive description down there), so, yeah.

**Review by Semisol — DISMISSED** [review]
Compiles.
App icon unchanged? (But splash is)
And the name at the "action bar"
image

**Comment by Semisol** [comment]
Don't merge, please. I would prefer some more feedback on the concerns listed above first.

And here is testing status: (please edit if you can to include more platforms!)

- [ ] Linux
  - [x] Arch
  - [x] Debian Sid (tested by @panos)
- [x] macOS
  - [x] Big Sur
- [x] Windows
  - [x] 10 (tested by @AnotherFoxGuy)

**Comment by n0toose** [comment]
Edited your comment after I successfully compiled and installed Tenacity in a Debian userland, @Semisol.

**Comment by Semisol** [comment]
> Edited your comment after I successfully compiled and installed Tenacity in a Debian userland, @Semisol.

Feel free to, very appeciated 😄

**Comment by AnotherFoxGuy** [comment]
Seems to build and run fine on Windows 10

**Comment by n0toose** [comment]
Let's just go for it!

**Comment by ajayyy** [comment]
> Compiles.
> App icon unchanged? (But splash is)
> And the name at the "action bar"
> image

Expected, this is only for changing the executable and folder names.

**Comment by n0toose** [comment]
Okay, the rebase seems to have worked, let's try pushing this to master itself.

**Comment by n0toose** [comment]
I tried to force-push twice to Ajayyy's tree because pushing the changes to master did not work ("a pushed branch tip is behind its remote counterpart") as a very likely result of diverging trees.

**Pull request merged**
