### PR TITLE
Vamp SDK filename fixes

### LINKED ISSUE #526: Windows build is broken by missing `vamp-hostsdk.dll`
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

Audacity-2.4.1-1824-ge36e909

### Describe the bug.

1. Configure using `cmake -B build`
2. Build using `cmake --build build`
3. Execute `./build/bin/Debug/Tenacity.exe`
4. Observe DLL missing dialog for `vamp-hostsdk.dll`

### Expected behavior

Tenacity should start up without the DLL missing error when built with default options.

### OS

Windows 10 Education 21H1 (Build 19043.1165)

### Additional context

image

The missing release DLL is present within `vcpkg\packages\vamp-sdk_x64-windows`, but it is not being copied to the output folder on Debug builds. It actually seems that it should be relying on the debug version of the DLL anyways.

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

### PR DESCRIPTION
**Pull request by Be-ing**
Resolves: #526

If the Windows build works, I'll merge the vamp_sdk_filename branch of the vcpkg repo to the tenacity branch and make a PR for upstream vcpkg.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by emabrey** [comment]
Your commit title starts with a lowercase letter.

**Comment by emabrey** [comment]
You need to pull the commits from my ~~YASM~~/NASM fixes to vcpkg on to your branch to prevent regression. (Just NASM actually, the YASM fix hasn't been merged yet).

https://github.com/tenacityteam/vcpkg/commit/149fdbc4420631ed04a8881642b45b7993335db4

**Comment by emabrey** [comment]
I tried this on my system locally with a Debug build, which is what my fix already successfully fixes, and I got this error:

```
LINK : fatal error LNK1104: cannot open file '..\vcpkg_installed\x64-windows\lib\vamp-hostsdk.lib' [C:\Users\emily\Documents\GitHub\tenacityteam-tenacity\build\src\Tenacity.vcxproj]
```

**Review by emabrey — CHANGES_REQUESTED** [review]
This needs to include my NASM workaround fixes for the vcpkg issue I addressed a few days ago. Additionally, this doesn't currently work and gives an error at link time.

**Comment by Be-ing** [comment]
>  got this error

vcpkg might not have rebuilt the package because I forgot to bump the port version before.

**Comment by Be-ing** [comment]
Debug build on GitHub Actions worked:
```
-- Found VampHostSDK: D:/a/tenacity/tenacity/build/vcpkg_installed/x64-windows/debug/lib/VampHostSDK.lib  
-- VAMP plugin hosting enabled.
```
Please test the current state of this branch locally.

**Comment by emabrey** [comment]
It worked. Shouldn't you be fixing this upstream though and not doing it as an overlay?

**Comment by Be-ing** [comment]
I am using the overlay to confirm it works before making an upstream pull request. It typically takes about a week for a pull request to be merged upstream. We don't need to wait for that before fixing it for ourselves. Once it is merged upstream we can remove the vamp-sdk package from our overlay.

**Comment by Be-ing** [comment]
Upstream vcpkg PR: https://github.com/microsoft/vcpkg/pull/20002

**Comment by Be-ing** [comment]
I cherry-picked the vamp-sdk fix and the NASM workaround to the `tenacity` branch of the vcpkg repo and switched the submodule back to the `tenacity` branch.

**Review by nbsp — CHANGES_REQUESTED** [review]
Can't directly review because it's in a submodule, but
[vcpkg/overlay/ports/vamp-sdk/vcpkg.json:](https://github.com/tenacityteam/vcpkg/blob/28bbf64ef21a564dd5c31828f36289bdc99796cd/overlay/ports/vamp-sdk/vcpkg.json#L6)
```json
  "description": "Library for VAMP plugins",
```

`VAMP => Vamp`

**Review by emabrey — DISMISSED** [review]

**Comment by Be-ing** [comment]
@solfisher that is extremely minor and inconsequential to Tenacity, but okay, fixed.

**Review by emabrey — DISMISSED** [review]

**Review by nbsp — DISMISSED** [review]

**Comment by emabrey** [comment]
@Be-ing Can you pull in upstream changes/force push to this branch before I merge this? I was about to do the merge but I noticed that the vcpkg commit is a reversion and I just want to be sure not to break master. Once you do that I will merge it since it's already approved.

**Comment by Be-ing** [comment]
Huh? What reversion are you referring to?

**Comment by Be-ing** [comment]
My [pull request](https://github.com/mixxxdj/mixxx/pull/4243#issuecomment-915185876) was merged upstream so I removed vamp-sdk from the overlay and merged the latest vcpkg upstream.

**Comment by Be-ing** [comment]
Merge?

**Review by n0toose — APPROVED** [review]

**Pull request merged**
