### PR TITLE
Use Tenacity.Project in AudacityApp.cpp

### LINKED ISSUE #333: AudacityApp.cpp uses different project file names
https://github.com/tenacityteam/tenacity/blob/2f316d5bc4e2c50dcd2a1c2360721030462e1d33/src/AudacityApp.cpp#L2275-L2295

Should the references there be changed to `Tenacity.Project` like other places, or would this affect previously created project files?

Either these need to be changed, or the other changes need to be reverted.

### PR DESCRIPTION
**Pull request by nbsp**
Signed-off-by: Sol Fisher Romanoff <sol@solfisher.com>

Resolves: https://github.com/tenacityteam/tenacity/issues/333

`src/AudacityApp.cpp` now uses `Tenacity.Project` instead of `Audacity.Project`. As far as I can see this doesn't create any problems with project importing/exporting to Audacity.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by Semisol** [comment]
## Testing checklist

- [ ] macOS
- [ ] Windows
- [ ] Linux
	- [x] Arch
	- [ ] Manjaro
	- [ ] Debian
	- [ ] Ubuntu
		- [ ] elementaryOS
	- [ ] Fedora
	- Other? Add it here.
	
I'll test later.

**Comment by n0toose** [comment]
[Person on what seemingly looks like Windows 11 experienced problems](https://fosstodon.org/web/statuses/106739731188187166) after "having imported an Audacity project and then having saved it as a Tenacity project". The Audacity version in use (Audacity 2.3.0) may possibly be too old. I'm not aware if 3.* projects are compatible, fork or not.

**Comment by JPcode05** [comment]
I'm wondering if we should change the name to TenacityApp.cpp

**Comment by n0toose** [comment]
> [Person on what seemingly looks like Windows 11 experienced problems](https://fosstodon.org/web/statuses/106739731188187166)...

[Same person confirmed that this worked on Windows 11 with Audacity 3.0.3.](https://fosstodon.org/web/statuses/106742152062460016)

**Comment by nbsp** [comment]
> [Same person confirmed that this worked on Windows 11 with Audacity 3.0.3.](https://fosstodon.org/web/statuses/106742152062460016)

1. Do projects from Audacity 2.3.0 import/export correctly to Audacity 3.0.3?
2. This needs checking with a more recent 2.x version, like 2.4.2
3. We could ignore the issue as "not our bug", since it deals with an old version of a different program.

**Comment by n0toose** [comment]
> > [Same person confirmed that this worked on Windows 11 with Audacity 3.0.3.](https://fosstodon.org/web/statuses/106742152062460016)
> 
>     1. Do projects from Audacity 2.3.0 import/export correctly to Audacity 3.0.3?

Based on the context, no. They tried importing the same project on 3.0.3 unsuccessfully.

>     2. This needs checking with a more recent 2.x version, like 2.4.2
>
>     3. We could ignore the issue as "not our bug", since it deals with an old version of a different program.

Your change is good to go.

**Review by n0toose — DISMISSED** [review]
Good to go!

**Pull request merged**
