### PR TITLE
Rename "Audacity" to "Tenacity" in Translatable Strings 

### PR DESCRIPTION
**Pull request by lmarz**
Part of: #508

The first commit replaces almost every occurence of "Audacity" with "Tenacity" in all Translatable Strings. Some are left in, because it wouldn't make sense replacing them (e.g. "Audacity Project file (.aup)"). The second commit is `update_po_files.sh` executed, so the changed strings can be translated on weblate.

This change also removes a lot of trailing spaces. VS Code does that automatically. I left them in because it doesn't hurt anyone and I realized my editor was doing this way too late

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Review by n0toose — APPROVED** [review]
Someone finally had to do this, as this was a huge blocker on our end. There are a lot of irrelevant style fixes, but I think that it's worth letting them slide because they majorly improve the quality of the codebase and many of the things that we want to backport need to be manually rewritten anyways because of compatibility.

**Comment by n0toose** [comment]
Only real issue here is that we may have some troubles with Weblate, I can also find a way to deal with that.

**Comment by n0toose** [comment]
@Semisol Is there any chance you could handle this?

**Comment by peepo5** [comment]
..

**Pull request closed without merging**
