### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/tenacity/tenacity/) for tenacity/tenacity.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by n0toose** [comment]
Can we space out the translations a little bit?

**Comment by emabrey** [comment]
@panos Why?

**Comment by n0toose** [comment]
For future reference: We should probably squash all of these commits before we merge them, it spams the commit log a lot.

**Comment by fitojb** [comment]
Weblate can squash by itself; I recommend the setting “Squash by author”.

**Comment by fitojb** [comment]
Neglecting to merge the updates has caused Weblate to emit an alert. https://hosted.weblate.org/projects/tenacity/tenacity/#alerts

@panos, we translators are not “spammers” as you imply. We are contributors, just like you, and should be on an equal footing with programmers. If somebody can add me as an admin, I can help you with the Squash Commits addon setting.

**Review by emabrey — DISMISSED** [review]

**Review by emabrey — APPROVED** [review]

**Pull request merged**
