### PR TITLE
update vcpkg submodule

### PR DESCRIPTION
**Pull request by Be-ing**
Pull package updates from vcpkg upstream. SoundTouch and PortMidi packages have been merged upstream so I removed them from the overlay.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by caughtquick** [comment]
The DCO check appears to be broken

**Comment by Be-ing** [comment]
Huh, I don't know what's going on with that. I don't think it's related to this PR though. The commit is signed off.

**Review by n0toose — APPROVED** [review]
I think it's safe to mention that you're more than free to also merge those pull requests yourself if enough time passes and nobody reacts, as you're the primary person responsible for these BTW.

**Comment by Be-ing** [comment]
I don't know what's going on with the DCO check. I can't merge from the GitHub web UI so I tried via CLI but that didn't work either:
```
tenacity on  master [$?⇡] via △ v3.22.1 
❯ git push upstream --force
Enter passphrase for key '/home/be/.ssh/id_rsa': 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "DCO" is expected.
To github.com:tenacityteam/tenacity.git
 ! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:tenacityteam/tenacity.git'
```

**Comment by n0toose** [comment]
Oh, give me a sec.

**Comment by n0toose** [comment]
Oh yeah, you can't merge this because admin permissions are needed to merge things, even if the tests don't pass. Taking the fact that the CI breaks literally every millisecond, I'll find a way to disable that for now one way or another.

CC: @tenacityteam/maintainers

**Comment by n0toose** [comment]
I just relaxed the requirements for a pull request to be merged (maintainers can merge pull requests without passed checks), which we put in the first place after I and other people made way too many mistakes as a result of pressure and trying to get a lot of work done, which led to some stuff getting accidentally merged, while bypassing our agreed due procedures. We agreed to generally relax the rules for contributions once the activity in the repository would die down.

I think it'd be a good idea for me to bring up that you and @emabrey should try to cooperate closely over these sorts of changes, if this is not happening right now, if possible. (I am currently trying to talk with her to properly discuss everything happening over here in further detail, just so that we're all on the same page here. :D)

**Comment by n0toose** [comment]
The only minor detail I would bring up is the capitalization in the commit, but eh, not even sure if anybody cares.

**Comment by Be-ing** [comment]
> cooperate closely over these sorts of changes

This is a very straightforward change, just pulling updates from upstream and getting rid of the obsolete custom ports in the overlay that are now upstreamed.

**Comment by n0toose** [comment]
I am just playing lame middle management here until we figure out what's going to happen and until I find more time, don't know, just brought it up, just in case.

**Pull request merged**
