### PR TITLE
Fix relative dir in build instructions

### PR DESCRIPTION
**Pull request by falkTX**
Since we `cd` to build dir, the `../audacity` cmake root dir path doesnt make sense.
Maybe it is intended to not create the build dir inside the code repo? In that case s/audacity/tenacity/ change is needed.

I didn't open a ticket about this, since it is not clear if the `build` dir should be created inside the tenacity source code folder or not.
It is often the case for building things with cmake that we create the build dir in the repo. If we create that outside, it can can conflict with any other project we have in parallel in the same directory that is already built (which can be an different copy of audacity for example), since all of them will be using the same ../build dir.

- [x] The code in this pull request is licensed under "GPLv2 or any later version"
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Review by fossdd — CHANGES_REQUESTED** [review]
Nope. You're wrong. In line 94 it clones Audacity ("Tenacity") in the `audacity` folder. And After that it does not change the PWD to that folder.

The structure should look like:

```
.
└ audacity
   ├ README.md
   ├ CMakeLists.txt
   └ ...
└ build
```
So your change is not required and is invalid

**Comment by falkTX** [comment]
That is only because the url https://github.com/cookiengineer/audacity is wrong.
I have a lot of source code in the same folder, this would mean having a dir named "build" side by side with the rest of these source folders.
Just seems very very odd to setup something like that. If trying to build tenacity and audacity side by side for comparison, we cannot use such folder setup as described in the instructions.

**Comment by Be-ing** [comment]
It is conventional to use `build` inside the repository root as the CMake build directory and list it in .gitignore (it is already in .gitignore).

**Comment by Qix-** [comment]
I've personally never (maybe once?) seen the directory structure where the build directory lives outside the root of the repository.

Is it possible? Absolutely, but it's way, way more common in terms of CMake convention to have a `build/` directory inside the repo and `.gitignore` it.

These changes make sense. I would have been confused by what was there before, too.

**Comment by falkTX** [comment]
Thanks for the extra feedback, I am not alone!
This PR conflicts with changes in #136 so better to merge that one first.

**Comment by falkTX** [comment]
Just added `cd tenacity &&` before the `mkdir build` to make this more obvious.

**Comment by Semisol** [comment]
Small reminder: Please sign off your commits. Do this by:
```
git rebase --signoff HEAD~<amount of commits not signed off>
git push --force-with-lease
```

**Pull request closed without merging**
