### PR TITLE
Remove test directory

### PR DESCRIPTION
**Pull request by emabrey**
This directory looks out dated. I need to check if the thing can just be removed wholesale.

Signed-off-by: Emily Mabrey <emilymabrey93@gmail.com>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by fossdd** [comment]
Doesn't break that any `make test` or so?

**Comment by Be-ing** [comment]
Maybe these tests just haven't been included in the build system since the switch to CMake? I'm not certain they should be removed.

**Comment by DimitarSamarov07** [comment]
Pretty sure these should stay

**Comment by mmmaisel** [comment]
The tests in the "octave" directory are working and test if the "Loudness" effect has regressions but they have to be executed manually. Please don't delete them.

**Pull request closed without merging**
