### PR TITLE
Weblate fix

### PR DESCRIPTION
**Pull request by emabrey**
Weblate merges are broken each and everytime I make a change and push it to upstream because I broke the history with some force-push abuse awhile ago (like last week) before I understood completely how the Weblate setup would work. This should fix that problem.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

### CODE REVIEW

**Comment by Semisol** [comment]
> with some force-push abuse awhile ago

The one with sign offs?

**Comment by emabrey** [comment]
> 
> 
> > with some force-push abuse awhile ago
> 
> The one with sign offs?

Yeah.

**Comment by Semisol** [comment]
Yeah that was bad.

**Comment by emabrey** [comment]
> 
> 
> Yeah that was bad.

🚫 🉑

**Pull request merged**
