### PR TITLE
Add licensing clarification

### PR DESCRIPTION
**Pull request by n0toose**
<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by caughtquick** [comment]
I'm not a fan of touching the license at all personally

**Comment by n0toose** [comment]
> I'm not a fan of touching the license at all personally

It's just a clarification that recites the same thing we already said in a more visible place. I don't really understand what's the problem here.

**Comment by caughtquick** [comment]
> > I'm not a fan of touching the license at all personally
> 
> 
> 
> It's just a clarification that recites the same thing we already said in a more visible place. I don't really understand what's the problem here.

I don't see a point in touching the license file at all. One mistake and that could cause us a lot of trouble

**Comment by n0toose** [comment]
> I don't see a point in touching the license file at all. One mistake and that could cause us a lot of trouble

Have you seen any such mistakes?

**Pull request closed without merging**
