### PR TITLE
Update names in the build instructions

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
The build instructions are technically broken (in a minor way) due to name changes.

# Changes
Update clone and build commands to match the new repository.

# Testing
This PR includes only changes I have used myself when building tenacity on Linux.  There may well be other changes needed for other platforms but as I have not built there I have not proposed such changes.

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] The code in this pull request is licensed under "GPLv2 or any later version"
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by falkTX** [comment]
Did you create the build dir parallel to the tenacity dir?
That seems a bit unusual, if you have more than 1 source code repo side by side, only 1 build dir can be there..
I think that is a bit unusual, see #126 

Would be best to `cd` into tenacity and create the build dir inside. Or am I missing something?

**Comment by HumbleDeer** [comment]
> Did you create the build dir parallel to the tenacity dir?
> That seems a bit unusual, if you have more than 1 source code repo side by side, only 1 build dir can be there..
> I think that is a bit unusual, see #126
> 
> Would be best to `cd` into tenacity and create the build dir inside. Or am I missing something?

You're not missing something; That's the most sensible thing to do. Multiple source dirs wouldn't be weird, as there's both stable and devel streams.

**Comment by bitdivine** [comment]
> Would be best to cd into tenacity and create the build dir inside. Or am I missing something?

Maybe.  I just followed the instructions and these are the minimal changes needed to make them work.  The instructions do specify to put the build directory next to the git repo, rather than inside it.  I have not changed that.  Personally, I agree, I would normally put the build dir inside the git repo but that is my policy and is not what the docs currently specify.  Policy change and fixes probably shouldn't be mixed in the same PR.  I would be 100% open to moving the build dir.  But:  If we change the location of the build dir we also need to check all the documentation, code and tests that might rely on the location of the build dir.  That is outside the scope of this PR.

**Comment by Semisol** [comment]
Small reminder: Please sign off your commits. Do this by:
```
git rebase --signoff HEAD~<amount of commits not signed off>
git push --force-with-lease
```

**Comment by purplesyringa** [comment]
I'm closing this because it looks like someone has already committed similar changes to `master`. I'm sorry we couldn't merge your PR due to DCO. Good luck next time!

**Pull request closed without merging**
