### PR TITLE
Implement toolbar edit mode

### LINKED ISSUE #122: Add Toolbar Edit Mode
Currently, the UI looks very cluttered. There is a lot of visual information to take in. As a first step to reduce the visual clutter, I think it might be a good idea to add a toggleable toolbar edit mode.

image

Disabling edit mode would hide these grabbers that appear to the left of every toolbar, and also the resizers that appear to the right of some toolbars:
image

On undocked toolbars, the grabbers should continue to appear because there is otherwise no way to drag the windows around. However, maybe docking them back to the main window should be prevented if edit mode is not enabled?

I think most people aren't customizing their toolbar layout while actively editing audio, so being able to hide these would not only make the UI look nicer, but also eliminate the chance of accidentally messing up the toolbar layout with a misclick.

And if some people are customizing their toolbar layout while actively editing audio, then they can just leave edit mode enabled.

### PR DESCRIPTION
**Pull request by abb128**
Resolves: https://github.com/tenacityteam/tenacity/issues/122

This implements a new checkbox under View > Toolbars > Edit Mode (on/off), and it is checked ON by default. Unchecking it disables grabbing and resizing toolbars, which makes the user interface slightly cleaner and prevents accidental drags.

ON (default):
image

OFF:
image

Undocked toolbars continue to have grabbers, but they cannot be docked back with the main window unless edit mode is re-enabled.

- [x] The code in this pull request is licensed under "GPLv2 or any later version"\*
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

### CODE REVIEW

**Review by fossdd — DISMISSED** [review]
Awesome patch.

**Review by emabrey — DISMISSED** [review]
I think this looks great!

**Comment by emabrey** [comment]
@fossd Did you mean to mark it as approved with your review?

**Review by fugidev — DISMISSED** [review]
Great patch! One small problem, we require all commits to be signed off, confirming that you agree to the DCO (check [CONTRIBUTING.md](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md) for details).
Please do `git rebase --signoff HEAD~8` to signoff the last 8 commits, then force push.
I will approve once that is done.

**Review by Semisol — DISMISSED** [review]
Your commits have been signed off with Github noreply emails. Please use an actual email which accepts mail. (Make a new one if needed).
It slipped through the bot.

**Comment by abb128** [comment]
I think I've got it now.

**Comment by Semisol** [comment]
I'll not be able to review this, anyways I have invalidated my request for changes so merging can be done.

**Review by fugidev — APPROVED** [review]
Looks all good now!

**Review by nbsp — APPROVED** [review]

**Pull request merged**
