### PR TITLE
Fix: Edit cursor coloring not being applied

### PR DESCRIPTION
**Pull request by akleja**
The specified color for the edit cursor is supposed to be returned when there's enough contrast, otherwise it returns the selection color as a fallback.
The specified color never got returned, and instead it returned null.
Also the part of the cursor in the ruler was hard coded black.
This prevents proper theming and accessibility.

This PR corrects the coloring of the edit cursor and matches the ruler part with the track part.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
Hi, thanks for your contribution! We'll take a look in a bit - for now, we'll test the change against our CI.

**Comment by akleja** [comment]
Hi, Thanks!
Just one clarification: It won't change the appearance of the cursor with any of the built in themes, except for the part of the edit cursor in the timeline on the dark theme.
This is mostly to make future theming better.

**Review by n0toose — DISMISSED** [review]

**Comment by Semisol** [comment]
reviewing...

**Review by Semisol — CHANGES_REQUESTED** [review]
Please **do not** push the dark mode to this PR that is supposed to be a fix and please open another PR instead.
You can create branches on your fork.

**Comment by akleja** [comment]
I'm so sorry! I'm new to git. Hopefully the reset made things right.

**Comment by n0toose** [comment]
> Please **do not** push the dark mode to this PR that is supposed to be a fix and please open another PR instead.
> You can create branches on your fork.

You know, that mode is so awesome to the point where I'd let it even slide! :P

**Review by n0toose — APPROVED** [review]

**Comment by Semisol** [comment]
> You know, that mode is so awesome to the point where I'd let it even slide! :P

Yep, it is awesome, but I do think it needs to be seperated.
Also, squash?

**Review by Semisol — APPROVED** [review]

**Pull request merged**
