### PR TITLE
Change macOS app icon

### PR DESCRIPTION
**Pull request by Semisol**
Resolves: Partially #441

Changes application icon to Tenacity (dark)
The project icons and installer need to be changed, along with the version being "**Audacity version** TAG-gCOMMITHASH"

P.S. Can someone else test this too?

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Review by nbsp — CHANGES_REQUESTED** [review]
Could you rename `Audacity.icns` to `Tenacity.icns`?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Shouldn't the icon fits with [modern guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) and looks like this one?

Icon-MacOS-512x512@2x

**Comment by nbsp** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Could you create a PR which uses this image, and also changes the icon filename?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@SFR-git I'll do it tomorrow, since I still need to update the project file icons and I've already turned off my work computer.

**Comment by nbsp** [comment]
Superseded by #556

**Pull request closed without merging**
