### PR TITLE
Increase retries in `repeat_hdiutil.sh` script

### PR DESCRIPTION
**Pull request by emabrey**
Increase both time between tries and number of tries.

Signed-off-by: Emily Mabrey <emabrey@tenacityaudio.org>

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Review by Semisol — COMMENTED** [review]
Can we just find a proper solution instead of a hack?

**Comment by emabrey** [comment]
Yeah you can fix CPack and make it not compete with MacOS Finder's iconcacheservice or whatever it is called. This is their official workaround, and there is no other way to fix it but to modify CPack.

**Comment by Be-ing** [comment]
I don't know if it is a coincidence or this branch makes the problem worse??? I've tried rerunning the build 3 times and it failed 3/3 times.

**Comment by emabrey** [comment]
> 
> 
> I don't know if it is a coincidence or this branch makes the problem worse??? I've tried rerunning the build 3 times and it failed 3/3 times.

We're dealing with a race condition problem so there is literally no telling if this makes it worse or better lol.

**Review by Be-ing — APPROVED** [review]

**Pull request merged**
