### PR TITLE
[Build] Prepared cmake for cmake-proxies removal

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
What started as a simple fix to get `find_package` working again ended up in a massive refactor of most of the cmake code for handling libraries

This theoretically also adds support for vcpkg, but haven't tested that yet

TODO list:
- [x] Test on Linux
	- [x] with conan
	- [x] without conan
- [x] Test on Windows 10
- [ ] Test on MacOS

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by Semisol** [comment]
I did a little amount of changes to the checklist.

**Comment by Be-ing** [comment]
I don't think this is a great idea for maintainability to make such extensive changes to the dependency finding code. In #228 I am bypassing that old code entirely and simply using `find_package` instead.

**Comment by Be-ing** [comment]
This is still using a lot of the vendored libraries. In #228 I already have it building without any vendored libraries except libnyquist due to the #included private header.

**Comment by AnotherFoxGuy** [comment]
> This is still using a lot of the vendored libraries.

I know, I will do the removal of the vendored libraries in a separate PR

**Pull request closed without merging**
