### PR TITLE
Update icons and logo to Tenacity

### LINKED ISSUE #223: Update splash screen and icons
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
When I launched this app, I couldn't tell if it was Audacity or Tenacity.

**Describe the solution you'd like**
I would like it if the splash screen read "tenacity" and not audacity.

**Describe alternatives you've considered**
Replace text on splash screen with "tenacity".

**Additional context**
I am not asking you to rebrand, just change the splash screen, perhaps into [something like this](https://imgur.com/a/h2zyfF2).

### PR DESCRIPTION
**Pull request by fossdd**
Signed-off-by: fossdd <fossdd@tutanota.com>

Resolves: https://github.com/tenacityteam/tenacity/issues/223

It does change all the icons and logos by Audacity to the Tenacity one. If you still see a Audacity logo or a blank icon please write a comment. I've tested it with Arch Linux and Sway, so someone has to look if the menu bar icon on macos, linux, windows is also changed.

I see that the images folder is really huge with binary images and so on. Is it maybe here better to put these in a external repo and use git submodules for this folder?

We still need #144 merged into master and rebased on it. Then the Ubuntu Linux installing and packaging issues are fixed. (.desktop icon entry and missing packages)

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by n0toose** [comment]
We should probably remove the old logos as well.

**Comment by fossdd** [comment]
Which do you mean?

**Comment by asperkraken** [comment]
On my Windows 10 Pro system, latest build, still getting all old graphics from Audacity on boot.
Boot is happening so fast i can't catch the launch graphic but it is still there.

Current Build Splash Screen, launching build from Visual Studio 19:
image


System Info:
image

**Comment by n0toose** [comment]
Can we even get this done before #144 is finished?

**Comment by fossdd** [comment]
> Can we even get this done before #144 is finished?

Then I have to add two things (changing project name in CMakeFiles.txt and adding some missing packages (https://github.com/tenacityteam/tenacity/pull/144/commits/df3c560c4de141a898add2cfca750accba9fc868)) that are in #144 but not in master.

**Comment by fossdd** [comment]
> On my Windows 10 Pro system, latest build, still getting all old graphics from Audacity on boot.

Okay, I try it myself

**Comment by fossdd** [comment]
Closing due to https://github.com/tenacityteam/tenacity/pull/276 which also fixes the windows icon.

**Pull request closed without merging**
