### PR TITLE
Change .aup3 MIMEtype to x-audacity-project

### PR DESCRIPTION
**Pull request by nbsp**
```
.aup3 isn't a Tenacity project file, it's just that Tenacity uses the
Audacity project file format.

Signed-off-by: Sol Fisher Romanoff <sol@solfisher.com>
```

Resolves: https://github.com/tenacityteam/tenacity/pull/632#discussion_r710949367

I would've expected there to be a lot more references to the MIMEtype, but I could only find 4 or 5.
This is ready for review, but marked as draft, since we haven't yet decided if we want to make this change.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Review by n0toose — APPROVED** [review]
I'm leaning towards yes. I share @leio's concerns about what we'll have to do on platforms like Windows and macOS, as in how will associations be managed without messing things up.

**Comment by emabrey** [comment]
This was changed intentionally to break us from their file format. Ideally we would support opening them but not writing them. If we have to support their file format for writing then we will end up in the GPL license trap we have discussed endlessly.

**Comment by n0toose** [comment]
Hold off from merging please, thanks.

**Comment by leio** [comment]
If we want to break away from their file format, we need to actually have our own file format first. Not claim the same files are ours instead and heavily clash with an audacity install claiming the same thing under a different name.

This is also all the old project file format in XML, the *.aup files of audacity2, not *.aup3 files of Audacity 3. We already don't support writing them, because they get migrated to aup3 instead, for which we don't even have a MIME type (neither does audacity).

We are trying to claim audacity2 XML files with _data subdirs are a tenacity project, even though we've never ever supported them beyond the inherited code to migrate them over to the sqlite-based `*.aup3`. This PR fixes this and should be merged.

The PR title is wrong though, because it's changing .aup MIMEtype, not .aup3

**Comment by n0toose** [comment]
I had to merge this as part of my efforts here (#694), can provide a more detailed explanation upon request, although most of what @leio said 4 months ago summed up most of it.

**Pull request merged**
