### PR TITLE
build PortAudio with ASIO support

### PR DESCRIPTION
**Pull request by Be-ing**
Signed-off-by: Be <be@mixxx.org>

Resolves: missing ASIO support on Windows

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by TimothyPeterson** [comment]
I hope this is the type of feedback you are looking for. 
Starting with the Build Info
BuildForASIO

Testing on Windows 10 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz  16.0 GB
No other sound sources were running ie. Zoom, Skype, audio players etc.

Mic/headset is (Shure MV51) USB Microphone. This is the Mic/Headset/Soundcard type of Microphones that is like the AT2020+ or the Blue Yeti. 

Reboot after ASIO4All install, version 2.14 - Testing with buffer set to 2048 and the default 512. 

Very high wait times to switch to ASIO, or to begin recording. In best case, after record was clicked, it took between 15 to 35 seconds to begin recording. 
Unfortunately, longer wait times led to freezes about 50% of the time. 

Note: Microphone labeling is taken over by ASIO4ALL and could be confusing to the user. See pic.
If there is another ASIO Driver you prefer, I would like to try that as well.
ASIO

On a brighter note Tenacity works on all other audio inputs! 
ASIO-BrightSide1

If there is another ASIO driver you would rather test with, Id be happy to give it a go.

**Comment by Be-ing** [comment]
ASIO4ALL adds a layer of indirection and has no benefit unless you're trying to use two different audio interfaces together.

**Comment by n0toose** [comment]
This confirms that the change you're trying to add is in, however, isn't it? (Thank you, @TimothyPeterson!)

There's another person that also stood forward to test out ASIO.

**Comment by Be-ing** [comment]
Yes, if ASIO4ALL can be selected this is working.

**Review by n0toose — DISMISSED** [review]
Fair enough! 🤞🏻

**Pull request merged**
