### PR TITLE
Remove `audacity_` prefix from CMake options

### LINKED ISSUE #127: Remove "audacity" from CMake option names
The CMake scripts prefix build options with `audacity_`. I don't think this prefixing is necessary at all. If others disagree, then it should be replaced with the new project name.

### PR DESCRIPTION
**Pull request by Be-ing**
Resolves: #127

The CMake build scripts prefixed all options with `audacity_`. This prefixing is not conventional nor necessary, and this is not Audacity anymore. :)

- [x] The code in this pull request is licensed under "GPLv2 or any later version"\*
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Comment by adrianheine** [comment]
You could keep `_OPT` but set to an empty string. That way the diff is smaller and we get less merge conflicts when pulling from upstream.

**Review by falkTX — DISMISSED** [review]
Please keep the _OPT as empty string, to reduce the diff

**Comment by Be-ing** [comment]
Good point. I will redo this later.

**Comment by Be-ing** [comment]
I minimized the diff but I need to be approved manually for the GH Actions job to run.

**Review by emabrey — DISMISSED** [review]

**Comment by Be-ing** [comment]
Merge?

**Review by adrianheine — APPROVED** [review]

**Review by n0toose — APPROVED** [review]

**Review by emabrey — APPROVED** [review]

**Comment by Be-ing** [comment]
This has 3 approvals. Why has it not been merged yet?

**Pull request merged**
