### PR TITLE
Fix and improve metadata file for Flatpak

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
- Remove bolding
- Fix APP ID typo
- Fix project license
- Add releases tags
- Migrate to metainfo from appdata
- Change screenshot
- Clarify metainfo license

Signed-off-by: TheEvilSkeleton <theevilskeleton@riseup.net>

Co-authored-by: Edgar <Edgar@AnotherFoxGuy.com>
Co-authored-by: Semisol <hi@semisol.dev>

No idea if it'll work or not, but I'm hoping this one is properly signed.

Resolves: https://github.com/tenacityteam/tenacity/commit/62a523f4f7324d5f28d9da9947995b72059905c4#commitcomment-54798902

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Looks like co-authors weren't signed properly:

>  We cannot verify signatures from co-authors, and some of the co-authors attributed to this commit require their commits to be signed. 

image

**Comment by Semisol** [comment]
You don't need to close it.
That is normal and co-authors in the current state of Git cannot sign commits.
And also, those signatures are GPG ones and are not related to the DCO.

**Comment by TheEvilSkeleton** [comment]
Is it Git or is it GitHub?

**Comment by Semisol** [comment]
Well, I just realized. You are referring to the DCO, which is not related to GPG signatures.
We can't fix that without force pushing which is unwanted, so no action is required on your part.

**Pull request closed without merging**
