### PR TITLE
Replace vendored libflac with libflac 1.3.3 using submodules

### PR DESCRIPTION
**Pull request by purplesyringa**
The first step toward resolving #200.

The rationale has been already discussed on #200 and IRC. I made some experiments with CMake and I think I figured out how to switch to submodules without breaking too much. I also updated libflac from 1.3.1 to 1.3.3 because it has quite a few bugfixes.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
Thanks for working on this but I don't think vendoring via Git submodules is much of an improvement. The most maintainable solution would be switching the vendored libraries to a package manager, either continuing with Conan as Audacity has started or switching to vcpkg. https://github.com/tenacityteam/tenacity/discussions/177

**Comment by falkTX** [comment]
please for the love of everything to do not do vendored dependencies in the git repo.
audacity has it wrong, placing it as submodule doesn't help the situation.

**Comment by n0toose** [comment]
> please for the love of everything to do not do vendored dependencies in the git repo.
> audacity has it wrong, placing it as submodule doesn't help the situation.

Many programs running on Linux allow you to either choose between the "built-in" version of a library and the operating system's version of a library. Not sure if this is worth something?

**Comment by purplesyringa** [comment]
As you please.

**Comment by falkTX** [comment]
> > please for the love of everything to do not do vendored dependencies in the git repo.
> > audacity has it wrong, placing it as submodule doesn't help the situation.
> 
> Many programs running on Linux allow you to either choose between the "built-in" version of a library and the operating system's version of a library. Not sure if this is worth something?

sometimes they do yes, but it is usually 1 or 2 essential libs.
audacity has more than 10.

**Pull request closed without merging**
