### PR TITLE
[Build] Added wxBase target

### LINKED ISSUE #641: Re-add wxBase alias
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

0.1.0, e776c2f

### Describe the bug.

The absence of a `wxBase` alias corresponding to `wxwidgets::widgets` blocks development.

https://github.com/audacity/audacity/blob/master/cmake-proxies/cmake-modules/dependencies/wxwidgets.cmake#L44-L46

### Expected behavior

Having these lines re-implemented would give us the option to pick up the work that the upstream Audacity project has been doing on cleaning up its codebase and separating different parts of its program in a singular `libraries` directory.

I already have a few patches lined up that were reconstructed on top of the Tenacity source code tree that took me 5 hours to make.

### OS

N/A

### Additional context

_No response_

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixes #641

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Review by n0toose — APPROVED** [review]
My experimental patches work just fine now!

Not sure if a comment with a brief explanation should be added on top of that (I can also do that myself), but this is fine.

**Comment by n0toose** [comment]
Super smart way to condense the entire thing as well, I love everything about this!

**Comment by AnotherFoxGuy** [comment]
I find it odd that we rely on libnyquist to find wxWidgets, but I have no idea why it has been set up like this

**Comment by n0toose** [comment]
wait what

**Comment by AnotherFoxGuy** [comment]
Nevermind, it seems that we just do two `find_package(wxWidgets)` calls

**Review by Be-ing — CHANGES_REQUESTED** [review]
What problem is this solving? This seems to be adding complexity for no benefit?

**Review by cklim074 — APPROVED** [review]

**Comment by n0toose** [comment]
> What problem is this solving? This seems to be adding complexity for no benefit?

We can separate different parts of the program into our own libraries -- like Audacity is doing. We can initially start off with their work and then carry on as we need it. This may be clearer once I send a patch in, but I'll have to document this a bit better. I'll explain in more detail later today.

**Comment by Be-ing** [comment]
I'm still not understanding what that has to do with this pull request.

**Comment by n0toose** [comment]
See this example, which applies for every other library in that folder itself as well: https://github.com/audacity/audacity/blob/97ca83e9a769da132322d87d342030d5525f7f80/libraries/lib-project/CMakeLists.txt#L22

For a more concrete example, try to cherry-pick 54b5f7d12c167f3905e1030648fc21a79f881e9c and see for yourself: It, as well as any other recent commit affecting the `libraries` directory, won't compile because of the `wxBase` alias thingy.

This will increase compatibility with the upstream source code. There are no `#include "audacity/example.h"` inclusions anymore and for other reasons too! Probably one of the few things that I've seen as "super good" in the development process of Audacity over the past 3 years. We can change that stuff later down the line. Not keeping up and leaving a half-finished mess is bad, this is a good enough compromise and delaying this in the absence of a better alternative is not a good idea. The end result, in exchange for this small addition to the CMake file, is much better than nothing. Could we please just move ahead with this, now?

**Comment by emabrey** [comment]
It looks like the Sourcehut CI is being affected by https://github.com/tenacityteam/tenacity/issues/640 . If that gets addressed in a separate PR and the changes merged in to this branch with CI passing totally, then I would be okay with merging this.

**Comment by n0toose** [comment]
I don't want to sound hostile, but from my point of view, I see this as completely freezing development over something that is not being actively worked on through a pull request *and* is not relevant. Why can't we get the job done?

**Comment by n0toose** [comment]
The SourceHut builds have been failing for the past I-do-not-know-how-many pull requests/commits.

**Comment by Paul-Licameli** [comment]
To give a clue what I'm thinking upstream.  wxBase is a subset of the non-monolithic build of wxWidgets.  It has many non-graphical things you might need to implement a command-line program, such as utilities for strings, files, atomics, timers, etc.

I want to allow many of the libraries I'm extracting to depend on it but exclude dependency on other parts of wxWidgets.

Yes, lots of those utilities might be preferably rewritten using the more modern C++ standard libraries that didn't exist yet when Audacity and wxWidgets were much younger.  But I think rewriting all of those uses is a misdirection of effort if you hope to change the UI toolkit.  Banishing the pervasive usage of wxString is more trouble than it's worth at this stage.  Resist the tempation to do that early, and leave it as a very distant future clean-up task, maybe.

**Comment by Be-ing** [comment]
> See this example, which applies for every other library in that folder itself as well: https://github.com/audacity/audacity/blob/97ca83e9a769da132322d87d342030d5525f7f80/libraries/lib-project/CMakeLists.txt#L22

So change that to `wxWidgets::wxWidgets`... why introduce this extra complexity? If you want to restrict the libraries to linking only wxBase, then create a target for that, but that's not what this branch does.

**Comment by n0toose** [comment]
It introduces a bigger maintenance-related burden on my end, but I guess I can handle that...

Sorry @AnotherFoxGuy, we should've seen that earlier on.

**Comment by Be-ing** [comment]
If you want to create a `wxWidgets::base` alias just for the base component that would be fine too. But this PR creating an alias called `wxBase` which is actually linking all of wxWidgets is misleading.

**Comment by n0toose** [comment]
Thank you for the explanation BTW, @Paul-Licameli.

**Pull request closed without merging**
