### PR TITLE
Fixed Audacity.Project regression, added own branding

### PR DESCRIPTION
**Pull request by n0toose**
What I tried to do here, as well as the alternative fixes I considered,
is way too large to explain. Long story short, I wanted to initially check
whether Tenacity.Project OR Audacity.Project was defined, but a typo as I was
formatting the change led to a logic error.

However, even if I did what I wanted to do, that would mean that we'd "lose"
our opportunity to ask the user whether they want to use Tenacity instead of
other programs. The Audacity developers basically already fixed the problem
that I was trying to fix, and the solution was right in front of us.

Apart from that, I also fixed a string so that the associated filetypes show
up as Tenacity Project Files. The user chose to associate them with Tenacity
anyway, so it makes perfect sense.

---

Note to reviewers: Since the latest commit caused a pretty big issue as a result of proceeding way too fast with merging without properly examining the consequences, it may be a good idea to just do the "push this to master ASAP" thing again if possible. Excuse the long commit message, but I believe that documenting the mindset behind certain decisions is important.

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
Hey, I slightly messed this up on at least two layers, but at least I got a much better understanding of how AudacityApp.cpp works, which is good in the end of the day.

**Comment by nbsp** [comment]
-1. I suggest reverting the last commit, then making the branding changes, which are unrelated to this problem.

**Comment by n0toose** [comment]
Dang it, forgot about the DCO ;_;

**Comment by n0toose** [comment]
This should be good to go, break initiated.

**Comment by nbsp** [comment]
s/Fixed/Fix, etc.

Other than that I think it's fine but I'm not gonna review this

**Review by emabrey — DISMISSED** [review]

**Review by fugidev — DISMISSED** [review]
works fine for me

**Comment by nbsp** [comment]
> s/Fixed/Fix, etc.

@panos could you rename the commits, and then merge?

**Pull request merged**
