### PR TITLE
Sync-lock improvements + minor theme fixes

### LINKED ISSUE #401: Sync-lock improvements
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
When editing with sync-lock enabled, it would be good to have a quick way of bypass it for minor edits, see https://github.com/tenacityteam/tenacity/discussions/388

**Describe the solution you'd like**
* Hold a modifier key to temporary override sync-lock
* Improve the visual representation of the synced tracks. Perhaps a patterned background of diagonal lines instead of the symbols

### PR DESCRIPTION
**Pull request by akleja**
Resolves: https://github.com/tenacityteam/tenacity/issues/401

Adds modifier key [alt] to temporarily override sync-lock which Improves the workflow when using synced tracks
Adds description of modifier to mouse bindings info in prefs.
Changes Background of synced tracks
Minor corrections of themes

New sync-lock background style:
Window002

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by nbsp** [comment]
Could you split this into two separate commits?

**Comment by akleja** [comment]
Yeah sure, but it will take a while. The whole process of exporting from svg to png, load in tenacity and export to theme files is a bit cumbersome.

**Comment by akleja** [comment]
Spitted into two commits done!

**Comment by nbsp** [comment]
Please rename your commits to match the guidelines!

```
Update themes
Improve sync-lock
```

**Comment by akleja** [comment]
Ok titles updated

**Comment by emabrey** [comment]
> 
> 
> Yeah sure, but it will take a while. The whole process of exporting from svg to png, load in tenacity and export to theme files is a bit cumbersome.

Can you contact me on element? I think that sounds like something that should be automated and I would be willing to write a script to do it if you can provide me the information I need about what tools you use etc.

**Comment by akleja** [comment]
@emabrey I just wanted to let you know I've finished writing the script (hope you didn't start as well)

But I'll wait with posting a PR until this one is either merged or closed.
The theme files that take the route through the program turns out a bit different, nothing that affects the appearance of the themes though.
So the current theme files should be replaced to match the output of the script, which will be messy if there are two parallel PR's that change the same files.
 I also made some small formatting changes and more sensible names of the theme files.

**Comment by emabrey** [comment]
> 
> 
> @emabrey I just wanted to let you know I've finished writing the script (hope you didn't start as well)
> 
> But I'll wait with posting a PR until this one is either merged or closed.
> The theme files that take the route through the program turns out a bit different, nothing that affects the appearance of the themes though.
> So the current theme files should be replaced to match the output of the script, which will be messy if there are two parallel PR's that change the same files.
> I also made some small formatting changes and more sensible names of the theme files.

Great! I did not start it yet, so no problems on that.

**Comment by TheWendyPower** [comment]
Thank you @akleja this looks like it will make workflow much smoother.

**Review by n0toose — APPROVED** [review]
We should add info about it in the status bar later on, and in other places as well.

**Review by fugidev — APPROVED** [review]
Very useful addition. I agree that a hint of its existence should be added later on, like #403 proposes (and/or maybe a popup when sync is first enabled?)

**Pull request merged**
