### PR TITLE
Correct commit ID location in bug report form

### PR DESCRIPTION
**Pull request by NotAProton**
Signed-off-by: Not a Proton <notaproton8@gmail.com>

New users don't know where to find the about dialogue.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] N/A I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by NotAProton** [comment]
image
 wat

**Comment by Semisol** [comment]
problem, your committer email hidden by github and it doesn't match the signoff so it errors out. you need a local clone to --amend the commit and force push it

**Comment by n0toose** [comment]
Hi, first of all, thank you so much for your contribution.

Another mistake you made here is the following: You signed this off manually and your e-mail doesn't have the `<>`'s. You can fix this mistake with the following command: `git commit --amend --signoff`. Then, you can force-push (`git push https://github.com/not-a-proton/tenacity.git patch-1`) to fix this.

**Comment by nbsp** [comment]
> Another mistake you made here is the following: You signed this off manually and your e-mail doesn't have the `<>`'s. 

No, it does. GitHub just omits the `<>` on Markdown.

```
Subject: [PATCH] Correct commit ID location in bug report form

Signed-off-by: Not a Proton <notaproton8@gmail.com>

**Comment by NotAProton** [comment]
Github has locked in the author as 
`Author: not-a-proton <81463636+not-a-proton@users.noreply.github.com>`

**Comment by NotAProton** [comment]
*sigh*

**Pull request closed without merging**
