### PR TITLE
Updating AboutDialog

### LINKED ISSUE #141: Rewriting the AboutDialog to fit the new project.
**Is your feature request related to a problem? Please describe.**
Right now the Tenacity AboutDialog is still the old Audacity one, it needs to be changed for rebranding.

**Describe the solution you'd like**
The AboutDialog should be reworked to fit the Tenacity project, with new content and links.

I have already started working on this and just want to have this out there, so we don't have multiple people working on the same thing at the same time again.

### PR DESCRIPTION
**Pull request by ThatVillagerGuy**
Resolves: #141 Rewriting the AboutDialog to fit the new project.
Updating the AboutDialog by removing Audacity stuff and changing the name to Tenacity.
Changes need to be translated at some point.

- [x] The code in this pull request is licensed under "GPLv2 or any later version"\*
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

### CODE REVIEW

**Review by falkTX — CHANGES_REQUESTED** [review]
Doesn't look good to me.
Lots of strings replaced on non-user-facing code, which will make upstream fetch/merge efforts more difficult.
Also lots of useless whitespace changes and line breaks changed for no real reason.

It is not your fault, since we do not have a guide for contributions just yet.
But generally try to change as little as possible.
This diff has many superfluous changes.

**Comment by JPcode05** [comment]
Some images I got on IRC showing the about dialog:
1. https://libera.ems.host/_matrix/media/r0/download/matrix.org/AWNlqggjdYxMbuPWnnBBEKyK/image.png
2. https://libera.ems.host/_matrix/media/r0/download/matrix.org/yLNQjcBEnieBMgXzSpXKHUhB/image.png

**Comment by fossdd** [comment]
<details><summary>Screenshots</summary><p>

image

image

image

</p></details>

Edit: oh @JPcode05 was faster

**Comment by falkTX** [comment]
I meant to say the code changes are a little problematic. but the intention is and looks good of course.
We just need to get there on a little different path.

**Comment by Semisol** [comment]
Small reminder: Please sign off your commits. Do this by:
```
git rebase --signoff HEAD~<amount of commits not signed off>
git push --force-with-lease
```

**Pull request closed without merging**
