### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
This MR updates the copyright to today's year (2022)

Signed-off-by: TheEvilSkeleton <theevilskeleton@riseup.net>

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

### CODE REVIEW

**Comment by n0toose** [comment]
Do you mind if I hijack your pull request and update the credits section on top of what you did?

**Comment by n0toose** [comment]
Nevermind, let's just merge this

**Comment by TheEvilSkeleton** [comment]
> Do you mind if I hijack your pull request and update the credits section on top of what you did?

@n0toose out of curiosity, what did you want?

**Comment by n0toose** [comment]
Update the credits window with the names/sites/aliases of all new contributors, etc.

**Comment by TheEvilSkeleton** [comment]
> Update the credits window with the names/sites/aliases of all new contributors, etc.

Do you know how we could find them? The Insights tab is quite overwhelming...

**Pull request merged**
